### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by Bratik17078** [PaperMC/Velocity#1012]
when is online-mode=false all ok but when its true velocity give me this error     
                            
 java.lang.IllegalStateException: Backend server is online-mode!
        at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.handle(LoginSessionHandler.java:79) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:87) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[17:06:23 INFO]: [connected player] Bratik17078 (/93.126.91.103:26313) has disconnected: Unable to connect you to hub. Please try again later.    
help please. Hub is also on online-mode and in the paper.yml also

**Comment by Malfrador** [comment]
> Hub is also on online-mode

That is the issue, as the error says. It needs to be in offline-mode because the proxy will do the authentication. See the [docs](https://docs.papermc.io/velocity/getting-started#after-launch).

In the future please use the [discord server](https://discord.gg/PaperMC) for support, not Github issues.
