### ISSUE TITLE
Teleporting between servers causes a ReadTimeoutException

### ISSUE THREAD

**Issue by iVillager** [PaperMC/Velocity#1014]
```
[15:09:04 INFO]: Problem login player
[15:09:04 ERROR]: java.util.concurrent.CompletionException: io.netty.handler.timeout.ReadTimeoutException
[15:09:04 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
[15:09:04 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
[15:09:04 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
[15:09:04 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[15:09:04 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
[15:09:04 ERROR]:       at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.exception(LoginSessionHandler.java:162)
[15:09:04 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.exceptionCaught(MinecraftConnection.java:170)
[15:09:04 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
[15:09:04 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
[15:09:04 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
[15:09:04 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[15:09:04 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeDecoderChannelHandler.exceptionCaught(ProtocolizeDecoderChannelHandler.java:111)
[15:09:04 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
[15:09:04 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
[15:09:04 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
[15:09:04 ERROR]:       at io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:98)
[15:09:04 ERROR]:       at io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
[15:09:04 ERROR]:       at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:503)
[15:09:04 ERROR]:       at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:475)
[15:09:04 ERROR]:       at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[15:09:04 ERROR]:       at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
[15:09:04 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:09:04 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:09:04 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:09:04 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[15:09:04 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:09:04 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:09:04 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:09:04 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[15:09:04 ERROR]: Caused by: io.netty.handler.timeout.ReadTimeoutException
[15:09:04 ERROR]: [server connection] Villag3r_ -> survival4: read timed out
```

**Comment by iVillager** [comment]
I was trying to teleport to my home using `HuskHomes Plugin`

**Comment by ham1255** [comment]
i am not sure if this should be considered a bug because if you read the stack trace 
`dev.simplix.protocolize.velocity.netty.ProtocolizeDecoderChannelHandler.exceptionCaught(ProtocolizeDecoderChannelHandler.java:111)`

**Comment by electronicboy** [comment]
That plugin in the trace is just a useless detail, outside of showing that there are plugins messing with the netty pipeline

But, this error is pretty much a typical time out, all we can tell is that the server didn't sent any packets in 30 seconds, this is pretty much moreso a support issue and best dealt with on discord if this is still a issue
