### ISSUE TITLE
Netty exception, potential conflict

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Velocity#1020]
```
[01:10:41] [Netty epoll Worker #1/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] <redacted> (/<redacted>): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@1bb6a195
io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: inflate data is bad
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.zip.DataFormatException: inflate data is bad
	at com.velocitypowered.natives.compression.NativeZlibInflate.process(Native Method) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at com.velocitypowered.natives.compression.LibdeflateVelocityCompressor.inflate(LibdeflateVelocityCompressor.java:59) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:69) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:34) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	... 29 more
```

I think Velocity's netty might be conflicting with another library that also uses netty that I use in a plugin. Do you think relocating netty could potentially fix this?

**Comment by Nacioszeczek** [comment]
A plugin should be relocating all of its dependencies ideally, yeah.
Leaving this open as a bug in case someone wants to take a look and it's not actually caused by a conflict.

**Comment by AoElite** [comment]
I've relocated all the dependencies & this still occurs sometimes but very rarely.

**Comment by 4drian3d** [comment]
As already mentioned, this is not a problem with Velocity but with the version of netty that has been included in another plugin incorrectly
