### ISSUE TITLE
Signature length not correct

### ISSUE THREAD

**Issue by SkyIce0229** [PaperMC/Velocity#1040]
`[07:22:16 ERROR]: Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213) ~[?:?]
        at java.security.Signature$Delegate.engineVerify(Signature.java:1435) ~[?:?]
        at java.security.Signature.verify(Signature.java:789) ~[?:?]
        at net.minecraft.util.SignatureValidator.verifySignature(SignatureValidator.java:30) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.SignatureValidator.lambda$from$3(SignatureValidator.java:54) ~[paper-1.20.1.jar:git-Paper-58]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at net.minecraft.util.SignatureValidator.from(SignatureValidator.java:50) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.SignatureValidator.validate(SignatureValidator.java:23) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.world.entity.player.ProfilePublicKey$Data.validateSignature(ProfilePublicKey.java:56) ~[?:?]
        at net.minecraft.world.entity.player.ProfilePublicKey.createValidated(ProfilePublicKey.java:28) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.network.chat.RemoteChatSession$Data.validate(RemoteChatSession.java:38) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatSessionUpdate(ServerGamePacketListenerImpl.java:3601) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.handle(ServerboundChatSessionUpdatePacket.java:19) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.a(ServerboundChatSessionUpdatePacket.java:9) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1386) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-58]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:22:16 INFO]: QuPIGll lost connection: Invalid signature for profile public key.
Try restarting your game.`

May I ask what caused this? I am sure that the secret filling in paper-global is correct, but I do not know why the connection cannot be made. Is it because non-local subservers are not supported

**Comment by 4drian3d** [comment]
This error is not from Velocity but from your Paper server, and seems to be caused by your client having an invalid signed key.
Try a vanilla 1.20.4 client and Paper 1.20.4 to see if it happens again
