### ISSUE TITLE
Error paper

### ISSUE THREAD

**Issue by ItsJaime** [PaperMC/Velocity#1043]
[21:21:35] [Server thread/ERROR] [minecraft/DedicatedServer]: Unable to load server configuration
java.lang.RuntimeException: Fatal paper.yml config error: Velocity support is enabled, but no secret key was specified. A secret key is required!
        at com.destroystokyo.paper.youcandfindpaper.PaperConfig.fatal(PaperConfig.java:77) ~[?:?] {re:classloading}
        at com.destroystokyo.paper.youcandfindpaper.PaperConfig.velocitySupport(PaperConfig.java:241) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at com.destroystokyo.paper.youcandfindpaper.PaperConfig.readConfig(PaperConfig.java:98) ~[?:?] {re:classloading}
        at com.destroystokyo.paper.youcandfindpaper.PaperConfig.init(PaperConfig.java:68) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:186) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:902) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:262) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
[21:21:35] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[21:21:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[21:21:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[21:21:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
        at net.minecraft.server.MinecraftServer.saveAllChunks(MinecraftServer.java:692) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1000) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:262) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by electronicboy** [comment]
That's not even an error from velocity, and the issue is in plain English
