### ISSUE TITLE
Getting Error On Join

### ISSUE THREAD

**Issue by zikehalil3535** [PaperMC/Velocity#1055]
[21:16:55 ERROR]: [server connection] WhiskeyTR -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@152aa053
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by zikehalil3535** [comment]
Turkish language shit fixed.
