### ISSUE TITLE
Strange error given thought from game

### ISSUE THREAD

**Issue by ejdzeys** [PaperMC/Velocity#1058]
Not always but occasionally I get an error like this I'm using the last build of velocity. I expect your help.

Logs:

> [20:03:03] [Netty NIO Worker #8/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [initial connection] /112.144.120.28:31256: read timed out
> [20:07:59] [Netty NIO Worker #4/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] Ejdzey -> lobi: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@5471c414
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-263.jar:3.2.0-SNAPSHOT (git-2aaf702a-b263)]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by electronicboy** [comment]
All we can see is that a connection was closed in an unexpected manner, this is generally not an issue with velocity itself

for support, please use the discord/forums

**Comment by ejdzeys** [comment]
My opinion is that this error is exactly on the velocity itself, because for some reason I don't get such an error on the Waterfall fork.

**Comment by electronicboy** [comment]
Theres no information to go off in which could dis/prove that, please use the discord/forums for support; Not going to flood peoples emails over what is at this point still a support issue

**Comment by ejdzeys** [comment]
very indifferent and rude attitude thanks!

**Comment by mbax** [comment]
Indifferent and rude would be dismissing the idea you are experiencing an issue at all. 

Instead, you were directed to *two* different options for getting support. 

Use one of those methods for support.

**Comment by ejdzeys** [comment]
If he was really a conscious official about this, I shared this error to him on discord yesterday and he didn't care about me :)

**Comment by mbax** [comment]
@ejdzeys [wrote](https://github.com/PaperMC/Velocity/issues/1058#issuecomment-1677842429)
> If he was really a conscious official about this, I shared this error to him on discord yesterday and he didn't care about me :)

He "didn't care" so much, he replied to you within ten minutes. Take further whining to another place - this is an issue tracker.

**Comment by electronicboy** [comment]
Posts on here generally ends up in peoples inboxes, there is no information here for me to act upon, and so this would require a back and forth in order to collate such information, which is generally a headache to do and needlessly spammy over github issues.

I also do not owe you my time (which is limited due to health, etc), and I'm trying to extend the means for a discussion here in order to try to diagnose what is going on, as there is nothing at all that is actionable here.
