### ISSUE TITLE
Issue with players trying to join and sometimes getting kicked with "connection to main encountered a problem"

### ISSUE THREAD

**Issue by shawn695** [PaperMC/Velocity#1069]
https://pastes.dev/U389FDnQCR

**Comment by electronicboy** [comment]
```
Caused by: io.netty.handler.codec.CorruptedFrameException: Bad string size (got 65, maximum is 16)
	at com.velocitypowered.proxy.protocol.util.NettyPreconditions.checkFrame(NettyPreconditions.java:83) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:199) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
```

Something, probably a plugin on your server, caused a mangled packet; can't look at the code, but, likely a plugin setting a name too large for a fake tab entry or something

**Comment by shawn695** [comment]
what do you mean for a fake tab entry ?

**Comment by shawn695** [comment]
and on the proxy or back end server

**Comment by electronicboy** [comment]
what I mean is that something is sending a player info packet with a string too large in there, the only string I'm aware of limiting to 16 characters is the name; which would stand to reason taht a plugin on your backend server is sending a tab list entry with a string which is too large, there'd be little reason for a plugin on the proxy to mess with it like that, but idk

**Comment by shawn695** [comment]
the only thing i have the changes player names and tags and tab is a pluggin called TAB on the proxy it bridges to the backend server

**Comment by shawn695** [comment]
are you able to give me more details ? im stripping pluggins from my back end server(s) and this is still happening

**Comment by shawn695** [comment]
```24.08 03:46:19 [Server] ERROR [server connection] Blazzin0420 -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@73a09b49
24.08 03:46:19 [Server] INFO io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo Direction CLIENTBOUND Protocol 1.20 State PLAY ID 3a
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
24.08 03:46:19 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid key bytes
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.crypto.EncryptionUtils.parseRsaPublicKey(EncryptionUtils.java:206) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.crypto.IdentifiedKeyImpl.<init>(IdentifiedKeyImpl.java:46) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.ProtocolUtils.readPlayerKey(ProtocolUtils.java:585) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.packet.chat.RemoteChatSession.<init>(RemoteChatSession.java:36) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo$Action.lambda$static$2(UpsertPlayerInfo.java:155) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo.decode(UpsertPlayerInfo.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:46:19 [Server] INFO ... 30 more
24.08 03:46:19 [Server] INFO [connected player] Blazzin0420 (/74.14.71.155:58794) has disconnected: Your connection to Main encountered a problem.
24.08 03:46:19 [Server] INFO [server connection] Blazzin0420 -> Main has disconnected
24.08 03:47:56 [Server] INFO [Main] (3): .Cobra0o094, KikiTheGame9444, .NovaWolves30
24.08 03:47:56 [Server] INFO 3 players are currently connected to the proxy.
24.08 03:48:41 [Server] INFO [connected player] Blazzin0420 (/74.14.71.155:58855) has connected
24.08 03:48:41 [Server] INFO [server connection] Blazzin0420 -> Main has connected
24.08 03:48:41 [Server] ERROR [server connection] Blazzin0420 -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@52203c5a
24.08 03:48:41 [Server] INFO io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo Direction CLIENTBOUND Protocol 1.20 State PLAY ID 3a
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
24.08 03:48:41 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid key bytes
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.crypto.EncryptionUtils.parseRsaPublicKey(EncryptionUtils.java:206) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.crypto.IdentifiedKeyImpl.<init>(IdentifiedKeyImpl.java:46) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.ProtocolUtils.readPlayerKey(ProtocolUtils.java:585) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.packet.chat.RemoteChatSession.<init>(RemoteChatSession.java:36) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo$Action.lambda$static$2(UpsertPlayerInfo.java:155) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo.decode(UpsertPlayerInfo.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
24.08 03:48:41 [Server] INFO ... 30 more
24.08 03:48:41 [Server] INFO [connected player] Blazzin0420 (/74.14.71.155:58855) has disconnected: Your connection to Main encountered a problem.```

**Comment by shawn695** [comment]
that is me just trying to get in game after getting kicked from one back end server going back main back end
 server
