### ISSUE TITLE
Kicked on join with: 'Lobby connection encountered a problem'

### ISSUE THREAD

**Issue by theprogrammerknownasat** [PaperMC/Velocity#1090]
I am trying to connect to my 1.18.2 velocity server. I am using velocity-3.1.2-SNAPSHOT-207 for my proxy server. On the backend, I am using 2 fabric 1.18.2 servers running these mods (see 1). When the client side says loading terrain, I get disconnected with '`Your connection to lobby encountered a problem`'. I launched the server with this flag: -Dvelocity.packet-decode-logging=true to get a more in-depth view of the packets. Here is the output of the velocity server (see 2). Here is the output of my fabric lobby server (see 3). Here is my client log (see 4). I am running the same mods on both of my fabric servers but with different worlds. 

1:
```
3dskinlayers-fabric-1.4.6-mc1.18.2.jar
advdebug-2.3.0.jar
architectury-4.11.93-fabric.jar
badpackets-fabric-0.1.3.jar
bettercombat-fabric-1.6.2+1.18.2.jar
brrp-fabric-1.0.1-1.18.2.jar
cloth-config-6.5.102-fabric.jar
Controllable-Mod-1.18.2.jar
create-fabric-0.5.1-c-build.1159+mc1.18.2.jar
CustomPlayerModels-Fabric-1.18-0.6.10a.jar
deepslategenerator-1.0.1+1.18.jar
EnvironmentalArmor-1.18.2-1.4.4.jar
extraorigins-1.18-11.jar
extra_classes_origins.jar
extshape-fabric-2.0.3-mc1.18.2.jar
fabric-api-0.76.0+1.18.2.jar
fabric-carpet-1.18.2-1.4.69+v220331.jar
fancymenu_fabric_2.14.9_MC_1.18.2.jar
firstperson-fabric-2.2.3-mc1.18.2.jar
geckolib-fabric-1.18-3.0.80.jar
Hephaestus-1.18.2-3.5.2.155.jar
HWGMod-1.18.2-1.1.11.jar.disabled
indium-1.0.7+mc1.18.2.jar
iris-mc1.18.2-1.6.9.jar
konkrete_fabric_1.6.1_MC_1.18-1.18.2.jar
lambdynamiclights-2.1.0+1.17.jar
lithium-fabric-mc1.18.2-0.10.3.jar
loadmyresources_fabric_1.0.4_MC_1.18-1.18.2.jar
logical_zoom-0.0.14.jar
medievalweapons-1.2.0.jar
midnightcontrols-1.5.0+1.18.jar
modmenu-3.2.5.jar
morevillagers-fabric-1.18.2-3.3.2.jar
New folder
notenoughanimations-fabric-1.6.0-mc1.18.2.jar
Origins-1.18.2-1.4.1.jar
Origins-Classes-1.18.2-1.3.0.jar
originsumbrellas-1.5.2.jar
Pehkui-3.7.8+1.14.4-1.20.1.jar
phonos-0.3+1.18.2.jar
phosphor-fabric-mc1.18.x-0.8.1.jar
player-animation-lib-fabric-1.0.2+1.18.jar
RoughlyEnoughItems-8.3.656.jar
ruined-equipment-2.0.0+1.18.jar
simplyswords-fabric-1.40-1.18.2.jar
sizeshiftingpotions-1.4.0.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
torohealth-1.18-fabric-2.jar
trinkets-3.3.1.jar
voicechat-fabric-1.18.2-2.4.24.jar
waveycapes-fabric-1.3.2-mc1.18.2.jar
worldedit-mod-7.2.10.jar
wthit-fabric-4.13.6.jar
```

2:
```
java -jar -Dvelocity.packet-decode-logging=true velocity-3.1.2-SNAPSHOT-207.jar
[20:25:20 INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-ffa4c954-b207)...
[20:25:20 INFO]: Loading localizations...
[20:25:20 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[20:25:20 INFO]: Loading plugins...
[20:25:20 INFO]: Loaded 0 plugins
[20:25:20 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[20:25:20 INFO]: Done (0.71s)!
[20:25:28 INFO]: [connected player] MasterCrampter19 (/127.0.0.1:50487) has connected
[20:25:28 INFO]: [server connection] MasterCrampter19 -> lobby has connected
[20:25:28 ERROR]: [server connection] MasterCrampter19 -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@3fce73c9
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.18.2 State PLAY ID 12
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
    at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:85) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:208) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:86) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.2-SNAPSHOT-207.jar:3.1.2-SNAPSHOT (git-ffa4c954-b207)]
    ... 32 more
[20:25:28 INFO]: [connected player] MasterCrampter19 (/127.0.0.1:50487) has disconnected: Your connection to lobby encountered a problem.
[20:25:28 INFO]: [server connection] MasterCrampter19 -> lobby has disconnected

```

3:
```
[20:25:28] [Server thread/INFO]: MasterCrampter19[/127.0.0.1:50491] logged in with entity id 326 at (17.5, 76.0, -46.5)
[20:25:28] [Server thread/INFO]: MasterCrampter19 joined the game
[20:25:28] [Server thread/INFO]: MasterCrampter19 lost connection: Disconnected
[20:25:28] [Server thread/INFO]: MasterCrampter19 left the game
```

4:
```
[20:31:33] [Render thread/INFO]: Connecting to localhost, 25565
[20:31:33] [Netty Client IO #21/INFO]: Connected to a vanilla server. Catching up missing behaviour.
[20:31:34] [Netty Client IO #21/INFO]: Decoded Weapon Attribute registry in 12 string chunks
[20:31:34] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='minecraft', name='overworld'} => NamespacedId{namespace='minecraft', name='overworld'}
[20:31:34] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='minecraft', name='overworld'}
[20:31:34] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[20:31:34] [Render thread/INFO]: Started 10 worker threads
[20:31:34] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:31:34] [Render thread/INFO]: [voicechat] Sending secret request to the server
[20:31:34] [Render thread/INFO]: [voicechat] Clearing audio channels
[20:31:34] [Render thread/INFO]: Stopping worker threads
```

**Comment by electronicboy** [comment]
You have a mod which is registering custom argument types in commands, you'll need a mod like [cross-stitch](https://modrinth.com/mod/crossstitch) to wrap them so it doesn't break the protocol encoding

**Comment by theprogrammerknownasat** [comment]
I just installed cross-stich and am still getting the exact same errors.

**Comment by electronicboy** [comment]
if the error still occurs with cross-stitch that would generally imply that some mod is registering its arguments into the wrong namespace, there is no real fix for that atm afaik (unless you wanna dig into the packet to work out what's in there), and not really something we can do anything about as such

**Comment by theprogrammerknownasat** [comment]
Okay, thanks for your help.

**Comment by theprogrammerknownasat** [comment]
I managed to fix the problem! My problem was because of the '`Hephaestus`' mod. I think this is because it registers itself as '`tconstruct`' which is a port of the tinkers construct mod for fabric. I just removed the mod, and everything worked perfectly. Again, thanks for the help!
