### ISSUE TITLE
Try to connect server on geyser (bugs,maybe)

### ISSUE THREAD

**Issue by PigeonMuyz** [PaperMC/Velocity#1099]
[03:12:34 ERROR]: [connected player] PigeonMuyz (/192.168.6.176:0): exception encountered in com.velocitypowered.proxy.connection.client.AuthSessionHandler@1869c5ec
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$428/0x0000000801050e60, Packet ID: 2
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityCompressionDisabler.write(GeyserVelocityCompressionDisabler.java:83) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at org.geysermc.geyser.network.netty.ChannelWrapper.writeAndFlush(ChannelWrapper.java:218) ~[?:?]
        at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:230) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at com.velocitypowered.proxy.connection.client.AuthSessionHandler.lambda$completeLoginProtocolPhaseAndInitialize$7(AuthSessionHandler.java:216) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$428/0x0000000801050e60, Packet ID: 2
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(11135) exceeds writerIndex(29): PooledUnsafeHeapByteBuf(ridx: 3, widx: 29, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:192) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:187) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:126) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        ... 30 more

**Comment by gamer50082** [comment]
It clearly states that you should report to via discord also may try geyser discord and send the logs & dump to them (/geyser dump)
