### ISSUE TITLE
Proxy crash. Error switching player connection to config state

### ISSUE THREAD

**Issue by kolderz** [PaperMC/Velocity#1112]
The Proxy crashed when this happened. Plugins using: Geyser, Floodgate
Velocity 3.2.0-SNAPSHOT (git-f884e049-b275)
```
[Netty epoll Worker #3/ERROR] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: Error switching player connection to config state:
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.setState(com.velocitypowered.proxy.protocol.StateRegistry)" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.setState(com.velocitypowered.proxy.protocol.StateRegistry)" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at com.velocitypowered.proxy.connection.client.ConnectedPlayer.lambda$switchToConfigState$9(ConnectedPlayer.java:1113) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 8 more
	```

**Comment by Robowarrior834** [comment]
[latest.log](https://github.com/PaperMC/Velocity/files/12929362/latest.log)

**Comment by 4drian3d** [comment]
Can you give more details about which client the player is using or if the player is a Bedrock client (in that case the problem would be with Geyser)

**Comment by 4drian3d** [comment]
I cannot reproduce this error with a Java client, if someone can reproduce the error with a Bedrock client, they should report it to Geyser
