### ISSUE TITLE
Help with "Modded: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@696b459f com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). For more information, launch Velocity with 

### ISSUE THREAD

**Issue by Robowarrior834** [PaperMC/Velocity#1113]
Hi All, 

I am trying to setup a Medivial MC fabirc server with velocity and I am getting the following error. I was able to get the server to work with veolcity by adding fabricproxylite however I now get this error.

[13:07:35 ERROR]: [server connection] RoboWarrior834 -> Modded: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@14be3234
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.20 State PLAY ID 10
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
        at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:87) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:210) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:88) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity-3.2.0-SNAPSHOT-275.jar:3.2.0-SNAPSHOT (git-f884e049-b275)]
        ... 30 more

**Comment by Robowarrior834** [comment]
[latest.log](https://github.com/PaperMC/Velocity/files/12929365/latest.log)

**Comment by 4drian3d** [comment]
Install [CrossStich](https://modrinth.com/mod/crossstitch), the error is because Velocity has received an unregistered command argument. CrossStich fixes this problem
