### ISSUE TITLE
1.20.2 doesn't work

### ISSUE THREAD

**Issue by gamingcodedev** [PaperMC/Velocity#1115]
[11:19:40 ERROR]: [connected player] DenNamen (/87.146.48.53:49421): exception encountered in com.velocitypowered.proxy.connection.client.AuthSessionHandler@721ee1f7
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.chat.SystemChat in CLIENTBOUND protocol 1.20.2 phase LOGIN
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.chat.SystemChat in CLIENTBOUND protocol 1.20.2 phase LOGIN
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:697) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:52) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        ... 11 more

**Comment by Xernium** [comment]
One of the proxy plugins is trying to send a chat message to the client way too early before the client can even accept those. Disable your plugins one by one until it stops and then check back with the author of the plugin
