### ISSUE TITLE
Error: Failed to initialize a channel. Closing: [id: 0xdb9a3fcf, L:/172.24.0.7:25565 - R:/162.55.6.40:42460]

### ISSUE THREAD

**Issue by buffolollo** [PaperMC/Velocity#1121]
[10:14:03 WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0xdb9a3fcf, L:/172.24.0.7:25565 - R:/162.55.6.40:42460]
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
        at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Sytm** [comment]
Seems to be an issue with the FastMOTD plugin, not Velocity itself

**Comment by Warriorrrr** [comment]
One of your plugins is using internals and needs to update, this is not a velocity issue
