### ISSUE TITLE
Problem with news version of velocity

### ISSUE THREAD

**Issue by TheSavior22** [PaperMC/Velocity#1122]
Good afternoon, yesterday I updated velocity from version 265 to version 276 and also updated my paper servers from 1.20.1 to 1.20.2, now I have 2 different problems, there is one that I have with some users who previously could enter the server, now they can enter the lobby but once they enter my paper 1.20.2 server the error that I will leave below occurs, they tried to join with different versions, eliminating the texture packs and the error still persists, I have the latest versions of paper and velocity, thank you
[19:17:53 ERROR]: [connected player] Clau215 (/190.162.184.14:50655): unable to connect to server Slimefun
java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.disconnected(ConfigSessionHandler.java:212) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:123) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueHandler.channelInactive(PlayPacketQueueHandler.java:81) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at java.lang.Thread.run(Thread.java:857) [?:?]

**Comment by TheSavior22** [comment]
and every time a user who has this problem and tries to enter the server, it kicks everyone connected to the server

Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [+] Clau215
[07:26:14] [Server thread/INFO]: Clau215[/190.162.184.14:59202] logged in with entity id 499552 at ([world]-6098.076630882258, 68.58749997615814, 2624.656771817179)
[07:26:14] [Server thread/INFO]: Haizen_Namikaze lost connection: Internal Exception: java.util.NoSuchElementException
[07:26:14] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [-] Haizen_Namikaze
[07:26:14] [Server thread/INFO]: Siyey lost connection: Internal Exception: java.util.NoSuchElementException
[07:26:14] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [-] Siyey
[07:26:14] [Server thread/INFO]: Clau215 lost connection: Internal Exception: java.util.NoSuchElementException
[07:26:14] [Server thread/WARN]: [O'DailyQuests] Player quests not found for player Clau215
[07:26:14] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [-] Clau215
[07:26:14] [Craft Scheduler Thread - 365 - ODailyQuests/INFO]: [O'DailyQuests] Haizen_Namikaze's data saved.
[07:26:14] [Craft Scheduler Thread - 320 - ODailyQuests/INFO]: [O'DailyQuests] Siyey's data saved.
[07:26:14] [Craft Scheduler Thread - 368 - ODailyQuests/WARN]: [O'DailyQuests] It seems that Clau215 disconnected before the end of the quest renewal.
[07:26:16] [Craft Scheduler Thread - 365 - EliteMobs/INFO]: [EliteMobs] Event dead_moon.yml ended!
[07:26:52] [User Authenticator #15/INFO]: UUID of player Siyey is 9253a167-7197-30d9-b99d-74f4a7ba28d3
[07:27:16] [User Authenticator #15/INFO]: UUID of player Clau215 is 9f2b8105-dd38-3209-961b-abf708ab137d
[07:27:16] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [+] Clau215
[07:27:16] [Server thread/INFO]: Clau215[/190.162.184.14:53140] logged in with entity id 500711 at ([world]-6098.076630882258, 68.58749997615814, 2624.656771817179)
[07:27:16] [Server thread/INFO]: Clau215 lost connection: Internal Exception: java.util.NoSuchElementException
[07:27:16] [Server thread/WARN]: [O'DailyQuests] Player quests not found for player Clau215
[07:27:16] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [-] Clau215
[07:27:16] [Craft Scheduler Thread - 330 - ODailyQuests/WARN]: [O'DailyQuests] It seems that Clau215 disconnected before the end of the quest renewal.
[07:27:23] [Server thread/INFO]: com.mojang.authlib.GameProfile@bf6a94e9[id=9253a167-7197-30d9-b99d-74f4a7ba28d3,name=Siyey,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTY5Nzk2NTI4NTEyNSwKICAicHJvZmlsZUlkIiA6ICI2ZDljZWYxZDU4NzY0ZjczODQ1ZTYwMmIxM2I2ODUzNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJIZWxlbm90YSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jOWI4MzlmNTI1NDBlYzc3YjIwOGU4NTZmNjM4OTA1OTgyZTZjYTk2NmNmYjFhYzI0OTIyMGQ1ZjM3MGJkMDVkIgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMzQwYzBlMDNkZDI0YTExYjE1YThiMzNjMmE3ZTllMzJhYmIyMDUxYjI0ODFkMGJhN2RlZmQ2MzVjYTdhOTMzIgogICAgfQogIH0KfQ==, signature=cq+m23N23iWHIXskTK6K8HJVykUVjUOUUbLNktjr9mkhtlRUnmRx6WcpwMIACdFJJidNKqBNUH+454W72pVn+KXFn2wx3ykZ17y6A63e4d5nwKwWqWS30FK4kmurd+Hviio4S1lksnR06sZeioeML237ynv/f+sHfvX32e+aOBOay4VUcnabiaCXd8+YHG8+nSuefbNY5AA5WjYZbKURczBedDgH5yafol2ewd5IC5et+33fK8S0DPd69JKmsq6PyazQyro5l4NHsSMYBPHsvY0zFABfjGfbGRUeyzSu8KZRmi0o3kUT8E2eIbEB2R3KlJ3ZL3LxD95t/mGGX86TrSsr9SCyoQLXxIZ0EReYP9lQrYOMAdUYnR/WcbZfb5yXcVXlDG70qyWGwQG6eqnKfklvoNQBhdF1F2cju1yVobjrspS4gzGVahG/K7JWJxA5tykhDt8wmdxiTaoNb+gYYZDDYS8bTcTojQEEWvrWpNjlVhycwgHpVXsp0OWS9MOB+xcAUSyTV8Uxa7arIDRM52ZUaSmbJsXmDomYrScqDZ5efwhvPzFMGeCABQxxja8Ae1jbzGK8gqnkYu+QbsX0zflQcuL6B98hfY0ThOjpBk5ZSUYAtzSuaRgl60gxhyu2QbDdU2vz1I7+SbwYfhBq4iXeub10e/wt9nbNJ2UMDMI=]]}] lost connection: Disconnected
[07:28:03] [User Authenticator #15/INFO]: UUID of player Siyey is 9253a167-7197-30d9-b99d-74f4a7ba28d3
[07:28:04] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [+] Siyey
[07:28:04] [Server thread/INFO]: Siyey[/91.243.158.55:59536] logged in with entity id 501449 at ([world]2983.300000011921, 19.0, -722.2136593451891)
[07:28:04] [Craft Scheduler Thread - 358 - ODailyQuests/INFO]: [O'DailyQuests] Siyey's quests have been loaded.
[07:28:05] [Craft Scheduler Thread - 332 - EliteMobs/INFO]: [EliteMobs] User 9253a167-7197-30d9-b99d-74f4a7ba28d3 data successfully read!
[07:28:09] [User Authenticator #15/INFO]: UUID of player Clau215 is 9f2b8105-dd38-3209-961b-abf708ab137d
[07:28:09] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [+] Clau215
[07:28:09] [Server thread/INFO]: Clau215[/190.162.184.14:34678] logged in with entity id 501698 at ([world]-6098.076630882258, 68.58749997615814, 2624.656771817179)
[07:28:09] [Server thread/INFO]: Siyey lost connection: Internal Exception: java.util.NoSuchElementException
[07:28:09] [Server thread/INFO]: [CustomJoinAndQuitMessages] : [INFO] [-] Siyey
[07:28:09] [Server thread/INFO]: Clau215 lost connection: Internal Exception: java.util.NoSuchElementException

**Comment by TheSavior22** [comment]
i found the error, it was a protocollib problem with a plugin, thanks for your time
