### ISSUE TITLE
[io.netty.channel.ChannelInitializer]: Failed to initialize a channel.

### ISSUE THREAD

**Issue by Danila767** [PaperMC/Velocity#1138]
```
[io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0xda1c6041, L:/172.19.0.20:25680 - R:/31.173.240.32:62546]
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
        at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Last Build
Java 18**

**Comment by KoxSosen** [comment]
Does this happen without plugins? If not, please report this issue to `net.elytrium.fastmotd`.

**Comment by electronicboy** [comment]
Outdated plugin messing with internals
