### ISSUE TITLE
Forge client cannot connect to Velocity

### ISSUE THREAD

**Issue by levitskyyy** [PaperMC/Velocity#1141]
### How to reproduce:

1. Set up Velocity 3.2.0-SNAPSHOT (git-8dcc7ee3-b294) and two paper servers.
2. Сonnect to the lobby with Forge and get an error. (there is no such error on the fabric version)

### Velocity
```
[connected player] _Klayn1_ (/xxx.xxx.xxx.xxx:xxxxx) has connected
[07:08:09 INFO]: [server connection] _Klayn1_ -> auth has connected
[07:08:10 INFO]: [connected player] _Klayn1_ (/xxx.xxx.xxx.xxx:xxxxx): kicked from server auth: Invalid payload REGISTER!
[07:08:10 INFO]: [server connection] _Klayn1_ -> auth has disconnected
[07:08:10 INFO]: [connected player] _Klayn1_ (/xxx.xxx.xxx.xxx:xxxxx) has disconnected: You were kicked from auth: Invalid payload REGISTER!
```

### Paper lobby
```
[07:08:10 INFO]: _Klayn1_[/xxx.xxx.xxx.xxx:xxxxx] logged in with entity id 52 at ([world]0.0, 0.0, 0.0)
[07:08:10 ERROR]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use )
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.addChannel(CraftPlayer.java:2354) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:146) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:46) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:12) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:08:10 INFO]: _Klayn1_ lost connection: Invalid payload REGISTER!
```

### Paper plugins

- AuthMe
- AuthMe-Velocity
- Chatty

### Velocity plugins

- LuckPerms Velocity
- AuthMe-Velocity
- Geyser-Velocity
- ViaVersion
- ViaBackwards

**Comment by electronicboy** [comment]
> java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use )

should contain the channel name, so, something is sending a bad channel name, and looking at this:

```
[08:06:33 INFO]: [connected player] electronicboy (/127.0.0.1:53245) has connected
[08:06:33 INFO]: [server connection] electronicboy -> server2 has connected
[08:06:33 INFO]: SERVERBOUND: minecraft:brand: "forge"
[08:06:33 INFO]: CLIENTBOUND: minecraft:brand: "Paper"
[08:06:33 INFO]: SERVERBOUND: minecraft:register: "forge:tier_sortingforge:handshakeforge:login"
[08:06:37 INFO]: [server connection] electronicboy -> lobby has connected
[08:06:37 INFO]: [server connection] electronicboy -> server2 has disconnected
[08:06:37 INFO]: CLIENTBOUND: minecraft:brand: "Paper"
[08:06:37 INFO]: SERVERBOUND: minecraft:register: ""
[08:06:37 INFO]: [connected player] electronicboy (/127.0.0.1:53245): kicked from server lobby: Invalid payload REGISTER!
[08:06:37 INFO]: [server connection] electronicboy -> lobby has disconnected
[08:06:37 INFO]: [server connection] electronicboy -> server2 has connected
[08:06:38 INFO]: CLIENTBOUND: minecraft:brand: "Paper"
[08:06:38 INFO]: [server connection] electronicboy -> server2 has disconnected
[08:06:38 INFO]: [connected player] electronicboy (/127.0.0.1:53245) has disconnected
```

that "thing" would seem to be the client, chances are forge is not liking the reset that occurs or something

**Comment by Xernium** [comment]
Your setup is unsupported. We don't support setups that cater to or allow piracy.
That said: The forge installation itself is most likely at fault. It tries to register a messaging channel with a blank identifier which is not allowed.
This is not a bug in Velocity. It's very intentional behavior.
The bug is in your forge client, you have to seek help elsewhere.
That said: Even if you "fixed" this bug on velocity by disabling this check **the server would also kick you for the same reason** since the check also exists there.

**Comment by levitskyyy** [comment]
> The bug is in your forge client, you have to seek help elsewhere.

but the problem is that this problem only occurs when using forge. when I connect to a regular server, paper - everything is fine. but when I connect from the forge client to the velocity proxy, this error comes out

**Comment by electronicboy** [comment]
Yes, because the forge client sent a bad registration packet. That's not on
us.
