### ISSUE TITLE
Disconnect on join

### ISSUE THREAD

**Issue by buffolollo** [PaperMC/Velocity#1182]
i got this error:

[21:11:30 ERROR]: [connected player] buffolollo (/ipaddress): exception encountered in com.velocitypowered.proxy.connection.client.AuthSessionHandler@5fdc018d
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.chat.SystemChat in CLIENTBOUND protocol 1.20.3 phase LOGIN
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.chat.SystemChat in CLIENTBOUND protocol 1.20.3 phase LOGIN
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:733) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:52) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
        ... 16 more

**Comment by Warriorrrr** [comment]
One of your plugins is sending a chat message to a player at too early a stage in the joining process, try removing plugins until the issue no longer happens. In the future, please also use the [discord](https://discord.gg/papermc) server for support
