### ISSUE TITLE
Connection issues on heavily modded fabric instance

### ISSUE THREAD

**Issue by nvb-uy** [PaperMC/Velocity#1184]
Hi! I'm testing velocity with my own modpack, [Prominence II [RPG]](https://modrinth.com/modpack/prominence-2-fabric)

Running a proxy with a single server for testing purposes, the server is using FabricProxy-Lite and is configured properly.

The first error was an owo lib issue which i resolved with their velocity plugin,
after that, I got this error right after loading the world:
![Error](https://cdn.discordapp.com/attachments/1073529888507691008/1194864017789943869/image.png)

Tried adding the CrossStich mod but it didn't fix the issue, same thing popped up.
Proxy logs don't show anything other than connection and disconnection.

*Edit: Wrong formatting for markdown*

**Comment by nvb-uy** [comment]
Must also mention that, at first I thought this was a krypton issue so I removed it, but the error persisted.

**Comment by Warriorrrr** [comment]
Does it show the exact same error even with krypton removed? It might be useful to start the proxy with -Dvelocity.packet-decode-logging=true or enabling debug on the backend to see if it says anything in the logs

**Comment by nvb-uy** [comment]
Yes, the error persists even without kyrpton, I'll try the debug in a bit.

I also want to point out that I did get this "fixed", by re-enabling packet compression, but I get kicked 2 seconds after joining with this error 
![ERROR](https://cdn.discordapp.com/attachments/1194862699587305524/1195056778057105520/image.png)

And the only print on the server's console is 
```
[11.01 19:28:37] [Disconnect] ElocinDev has disconnected, reasonDisconnected
[11.01 19:28:37] [Server] [Server thread/INFO]: ElocinDev left the game
[11.01 19:28:37] [Server] [Server thread/INFO]: remove player wand
```

On the proxy it only shows:
```
[11.01 19:28:33] [Server] [INFO] [connected player] ElocinDev (/*****) has connected
[11.01 19:28:33] [Server] [INFO] [server connection] ElocinDev -> lobby has connected
[11.01 19:28:37] [Server] [INFO] [connected player] ElocinDev (/*****) has disconnected: §cYour connection to lobby encountered a problem.
```

**Comment by nvb-uy** [comment]
This is what's shown now in the proxy

```
[11.01 19:54:55] [Server] [ERROR] [connected player] ElocinDev (/*****): unable to connect to server lobby
[11.01 19:54:55] [Server] io.netty.channel.AbstractChannel$AnnotatedConnectExceptionfinishConnect(..) failed: Connection refused: /*****
[11.01 19:54:55] [Server] Caused byjava.net.ConnectException: finishConnect(..) failed: Connection refused
[11.01 19:54:55] [Server] 	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[customjava17.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
[11.01 19:54:55] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[11.01 19:54:55] [Server] [INFO] [connected player] ElocinDev (/*****) has disconnected: §cUnable to connect you to lobby. Please try again later.
```

**Comment by electronicboy** [comment]
connection refused just says that the target host refused the connection, that is out of bounds of velocity

**Comment by nvb-uy** [comment]
Yet this only happens with Velocity... going back to a simple server works just fine...

**Comment by electronicboy** [comment]
connection refused is generally down to a network configuration issue, velocity itself has 0 control over your network and it's setup; Outside of that, your OG issue is however different, but, without much to work on here, theres little we can say or look into, we do not have the capacity to start debugging issues surrounding mod packs unless people can isolate it down to specific behaviors which are not instances of mods breaking the vanilla protocol spec

**Comment by nvb-uy** [comment]
After enabling the debug logging, here's the issue:

[18:39:50 ERROR]: [server connection] newtykins -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@24b2045f
io.netty.handler.codec.CorruptedFrameException: Uncompressed size 8734075 exceeds hard threshold of 8388608

**Comment by electronicboy** [comment]
So, you have a packet which exceeds the maximum packet size allowed by the vanilla protocol spec

**Comment by nvb-uy** [comment]
The modpack currently uses ETP which increases the limit and allows issues like these to not happen, iirc this is caused by a REI packet, at least outside of the proxy relation

https://www.curseforge.com/minecraft/mc-mods/extra-thicc-packets

Is there any plugin or anything that could maybe increase the limit for the proxy? As this definetly works per-server at least

**Comment by electronicboy** [comment]
No, not afaik, we make many assumptions based upon these limits and adding a means to disable that limit is not something we can do blindly

**Comment by nvb-uy** [comment]
It would be nice at least for modded servers, as a lot of modpacks require mods like these. I'll sniff the packets to look to the faulty one in the meantime, but an option to increase its maximum size would be ideal, there's no actual need to put it to the max integer value, but giving a choice for people to choose their own limit when things like these happens

**Comment by electronicboy** [comment]
there are technical caveats which arise elsewhere due to the design of the protocol which stem from this, could maybe 1.5x the limit safely, but too much beyond that will start causing some issues

**Comment by nvb-uy** [comment]
a 1.5x limit would be nice, at least for my use case

**Comment by nvb-uy** [comment]
do you know where I could modify this value? I can fork velocity in the meantime and test if it works with that change

**Comment by electronicboy** [comment]
oh, wait, run with `-Dvelocity.increased-compression-cap=true`, will set the cap to 128MB, I thought that would cause issues, but, I guess if it's just passthrough packets it shouldn't break much

**Comment by nvb-uy** [comment]
I'll try that out in a bit and let you know, thanks

**Comment by nvb-uy** [comment]
This is coming up now

```
[19:02:33 ERROR]: [server connection] newtykins -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@3977ed98
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.20 State PLAY ID 10
```

**Comment by electronicboy** [comment]
that is what cross stitch is generally for

**Comment by nvb-uy** [comment]
Will try with that, I did notice though, it only seems to support up to 1.19.3?

**Comment by nvb-uy** [comment]
That seems to have worked! Thanks a lot :)

**Comment by kaelianbaudelet** [comment]
Your problem is interesting, we're not the only ones who want to make a **velocity network** with the **Prominence II modpack**, what's interesting is that you've managed to solve the problem, could you explain how you did it, thanks to you you could greatly help the Prominence II community.

> That seems to have worked! Thanks a lot :)

**Comment by nvb-uy** [comment]
Yes I am aware as I am the creator of Prominence. I’ve already fixed this issue on default serverpacks, you just have to switch the jar to velocity. Alternatively copy the launch options from the serverpack into your new proxy’s launch args

**Comment by NotMurky** [comment]
Hey! I don't know if this is the right place, but I've debugging for couple of days now annnd kinda going crazy lol. 
I'm trying to use Velocity with two backend Fabric server running "Prominence II (v3.1.50hf)".
Currently I've added an oWo velocity plugin to correctly handle the handshake for oWo. Then I realised the some packets where exceeding the max size, I used  -Dvelocity.increased-compression-cap=true  in the launch args for Velocity and now I'm receiving this error 
Exception caught while decoding frame for /127.0.0.1:25577 com.velocitypowered.proxy.util.except.QuietDecoderException: VarInt too big
I've added no extra mods (Other then fabricproxylite, crossstitch),  to modpack, I'm using the default serverpack given by curseforge. Are there anyways around this error? The server has a mod called extra thicc packets which increaces the maximus packet size allowed by vanilla proc, I have not sniffed at what is causing this

**Comment by kaelianbaudelet** [comment]
Hey @NotMurky 👋

I actually ran into the exact same issue quite a while ago, drove me a bit crazy too haha. I don’t remember the exact fix, but I just had to tweak my server config a bit and it started working.

I had fabricproxylite and crossstitch like you and changed some config in one of them. After that, no more Velocity issue.

I’d recommend checking out the LunaPixel Studio Discord — I posted the full fix there back then, with all the details. You should be able to find my old message and it might help you get everything working, especially with those “extra thicc” packets 😅

See: https://discord.com/channels/790272037578473512/1302670370297483324

**Comment by NotMurky** [comment]
The solution in the discord server was simply adding crosss-stitch to fabric and adding compression flags to velocity. I have already done this, I've double checked to make sure I was not tweaking lol. Since the server side VarInt is set to infinite because of the mod packetfixer, but on Velocity side its the default value annnd it dont like that. I don't know what else to do other then start removing important mods that make this modpack. Unless I missed something important in the discord messages. A plugin for velocity would be wonders that deals with that. If I get rid of all packet modifying mods the varint issue goes to the backend server rather then velocity side. I'm open to trying anything lol, I just need something

**Comment by electronicboy** [comment]
The frame decoder only supports a packet length being encoded into 3 bytes, sending anything larger than that will produce the error seen; there is no means of working around this at present

**Comment by NotMurky** [comment]
I see.. Thank you for the information. I'll fiddle around some more.
