### ISSUE TITLE
Velocity does not respect system/java HTTP proxy settings

### ISSUE THREAD

**Issue by pan90** [PaperMC/Velocity#1188]
I use the following command line to start volecity:

`java -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=10808 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=10809 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=10809 -Djava.net.useSystemProxies=true -jar velocity-3.3.0-SNAPSHOT-320.jar`

But I found it didn't work.
However, it worked when I used these parameters to start my folia server:

`java -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=10808 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=10809 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=10809 -Djava.net.useSystemProxies=true -jar server.jar nogui`

```
[16:35:45 ERROR]: Unable to authenticate with Mojang
java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: sessionserver.mojang.com/13.107.246.74:443
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at com.velocitypowered.proxy.connection.client.InitialLoginSessionHandler.lambda$handle$4(InitialLoginSessionHandler.java:233) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at org.asynchttpclient.netty.NettyResponseFuture.lambda$addListener$0(NettyResponseFuture.java:294) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: connection timed out: sessionserver.mojang.com/13.107.246.74:443
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        ... 8 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/13.107.246.74:443
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        ... 8 more
```

**Comment by electronicboy** [comment]
Velocity does not use java networking stack, this will have to be dealt with manually at some point

**Comment by pan90** [comment]
So what is the way to set up a network proxy for volecity?

> Velocity does not use java networking stack, this will have to be dealt with manually at some point

**Comment by electronicboy** [comment]
At the moment, there is none, need to adopt nettys proxy handler

**Comment by astei** [comment]
I'd rather junk AsyncHttpClient and replace it with Java's own `HttpClient` which will probably just handle this out of the box
