### ISSUE TITLE
Got an unexpected error code Optional.empty whilst contacting Mojang to log in Sky_Ice_

### ISSUE THREAD

**Issue by SkyIce0229** [PaperMC/Velocity#1195]
If I use authlib-injector to log in to the server, I get ` [00:36:54 ERROR]: Got an unexpected error code Optional.empty whilst contacting Mojang to log in Sky_Ice_ (119.34.176.119)`
This is my log file 
`C:\Users\Administrator\Desktop\SyncServer\velocity>java -Xms512M -Xmx512M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -javaagent:authlib-injector-1.2.4.jar=https://skin.missice.xyz/api/yggdrasil -Dpaper.disableChannelLimit=true -jar velocity-3.3.0-SNAPSHOT-325.jar
[authlib-injector] [INFO] Logging file: C:\Users\Administrator\Desktop\SyncServer\velocity\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.4
[authlib-injector] [INFO] Authentication server: https://skin.missice.xyz/api/yggdrasil
[00:40:42 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-6d7335b2-b325)...
[00:40:42 INFO]: Loading localizations...
[00:40:42 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[00:40:42 INFO]: Loading plugins...
[00:40:42 INFO]: Loaded plugin minimotd-velocity 2.1.0 by jmp
[00:40:43 INFO]: Loaded plugin papiproxybridge 1.5 by William278
[00:40:43 INFO]: Loaded plugin velocitab 1.6 by William278
[00:40:43 INFO]: Loaded plugin viaversion 4.9.2 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[00:40:43 INFO]: Loaded 4 plugins
[00:40:43 INFO] [papiproxybridge]: PAPIProxyBridge (Velocity) has been enabled!
[00:40:43 ERROR]: Couldn't pass ProxyInitializeEvent to velocitab
net.william278.velocitab.libraries.configlib.ConfigurationException: The configuration file at plugins\velocitab\config.yml does not contain valid YAML.
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:135) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[?:?]
        at net.william278.velocitab.config.ConfigProvider.loadSettings(ConfigProvider.java:63) ~[?:?]
        at net.william278.velocitab.Velocitab.loadConfigs(Velocitab.java:125) ~[?:?]
        at net.william278.velocitab.Velocitab.onProxyInitialization(Velocitab.java:98) ~[?:?]
        at net.william278.velocitab.Lmbda$7.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-325.jar:3.3.0-SNAPSHOT (git-6d7335b2-b325)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-325.jar:3.3.0-SNAPSHOT (git-6d7335b2-b325)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-325.jar:3.3.0-SNAPSHOT (git-6d7335b2-b325)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.snakeyaml.engine.v2.exceptions.YamlEngineException: java.nio.charset.MalformedInputException: Input length = 1
        at org.snakeyaml.engine.v2.scanner.StreamReader.update(StreamReader.java:283) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:239) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:234) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.peek(StreamReader.java:189) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1114) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:292) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:444) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.lambda$produce$1(ParserImpl.java:232) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.produce(ParserImpl.java:232) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.peekEvent(ParserImpl.java:206) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.checkEvent(ParserImpl.java:198) ~[?:?]
        at org.snakeyaml.engine.v2.composer.Composer.getSingleNode(Composer.java:127) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadOne(Load.java:110) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadFromReader(Load.java:134) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:130) ~[?:?]
        ... 12 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
        at java.io.BufferedReader.read1(BufferedReader.java:213) ~[?:?]
        at java.io.BufferedReader.read(BufferedReader.java:287) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.update(StreamReader.java:246) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:239) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:234) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.peek(StreamReader.java:189) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1114) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:292) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:444) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.lambda$produce$1(ParserImpl.java:232) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.produce(ParserImpl.java:232) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.peekEvent(ParserImpl.java:206) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.checkEvent(ParserImpl.java:198) ~[?:?]
        at org.snakeyaml.engine.v2.composer.Composer.getSingleNode(Composer.java:127) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadOne(Load.java:110) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadFromReader(Load.java:134) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:130) ~[?:?]
        ... 12 more
[00:40:43 INFO] [viaversion]: Loading block connection mappings ...
[00:40:43 INFO] [viaversion]: Replacing channel initializers; you can safely ignore the following two warnings.
[00:40:43 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:43 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:43 INFO] [viaversion]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[00:40:43 INFO] [viaversion]: Highest supported version by the proxy: 1.20.3 (765)
[00:40:43 INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
[00:40:43 INFO]: Listening on /[0:0:0:0:0:0:0:0]:30061
[00:40:43 INFO]: Done (1.04s)!`

**Comment by SkyIce0229** [comment]
I'm sorry, this is it`[00:40:43 INFO] [viaversion]: Loading block connection mappings ...
[00:40:43 INFO] [viaversion]: Replacing channel initializers; you can safely ignore the following two warnings.
[00:40:43 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:43 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:43 INFO] [viaversion]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[00:40:43 INFO] [viaversion]: Highest supported version by the proxy: 1.20.3 (765)
[00:40:43 INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
[00:40:43 INFO]: Listening on /[0:0:0:0:0:0:0:0]:30061
[00:40:43 INFO]: Done (1.04s)!
> [authlib-injector] [INFO] Httpd is running on port 52564
[authlib-injector] [INFO] Transformed [com.velocitypowered.proxy.connection.client.InitialLoginSessionHandler] with [Constant URL Transformer]
[00:42:28 ERROR]: Got an unexpected error code Optional.empty whilst contacting Mojang to log in Sky_Ice_ (119.34.176.119)
[00:42:28 INFO]: [initial connection] /119.34.176.119:36600 has disconnected: multiplayer.disconnect.authservers_down
>`

**Comment by astei** [comment]
We don’t support garbage that only exists for piracy. There’s already an undocumented setting to change the Mojang session server if you must but if it doesn’t work you are on your own
