### ISSUE TITLE
How to use Chinese names as server names?

### ISSUE THREAD

**Issue by MCFurina** [PaperMC/Velocity#1227]
[14:45:39] [main/INFO] [com.velocitypowered.proxy.VelocityServer]:  Booting up Velocity 3.3.0-SNAPSHOT (git-38558783-b345)...
[14:45:39] [main/INFO] [com.velocitypowered.proxy.VelocityServer]:  Loading localizations...
[14:45:39] [main/INFO] [com.velocitypowered.proxy.network.ConnectionManager]:  Connections will use NIO channels, Java compression, Java ciphers
[14:45:39] [main/ERROR] [com.velocitypowered.proxy.VelocityServer]:  Unable to read/load/save your velocity.toml. The server will shut down.
com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: 登录服
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:176) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:146) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:56) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:102) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:103) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:52) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:454) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.velocitypowered.proxy.VelocityServer.doStartupConfigLoad(VelocityServer.java:334) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:235) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]

**Comment by RealmKebab** [comment]
you (probably) cant

**Comment by electronicboy** [comment]
Yes, but no. if you quote the string it can be added just fine, but there is a bug with mojangs command library which prevents parsing it as an argument
