### ISSUE TITLE
Resource Pack Errors on join/switching servers

### ISSUE THREAD

**Issue by NiceKaleido** [PaperMC/Velocity#1247]
Hello, 
I was told to open an issue on here for my current problems with the latest velocity verison (#430)

Whenever a player joins or switches the server I get errors like the attached one on the respective server the player tries to connect to. 
In case of a server switch that always leads to a disconnect after time out. In case of the first join it sometimes does lead to a disconnect. 

```
[12:07:31 INFO]: UUID of player NiceRon is 5f0ba907-87e2-49be-b621-3820a644f0b3
[12:07:34 ERROR]: Failed to handle packet ServerboundResourcePackPacket[id=e80cfd96-d878-36a2-b45d-e5d8ffbb7928, action=SUCCESSFULLY_LOADED], suppressing error
java.lang.IllegalStateException: Unexpected request for task finish, current task: join_world, requested: server_resource_pack
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.finishCurrentTask(ServerConfigurationPacketListenerImpl.java:168) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleResourcePackResponse(ServerConfigurationPacketListenerImpl.java:102) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-430]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by chasertw123** [comment]
I also have had this issue, narrowed it down to first occurring in 3.3.0-350.
