### ISSUE TITLE
unable to connect to hub

### ISSUE THREAD

**Issue by AminoPlays** [PaperMC/Velocity#1252]
when i join the server it shows a error
io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

in velocity
```[tasklist]
### Tasks
```

**Comment by electronicboy** [comment]
This is not the full error and is generally down to network configuration issues, please use the discord for support
