### ISSUE TITLE
Does Velocity use a port other than 25565?

### ISSUE THREAD

**Issue by waterghost-2046** [PaperMC/Velocity#1255]
[11:53:51] [Netty epoll Worker #6/ERROR] [com.velocitypowered.proxy.connection.client.InitialLoginSessionHandler]:  Unable to authenticate player
java.util.concurrent.CompletionException: java.net.ConnectException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1189) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341) ~[?:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:454) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:450) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
        at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372) ~[?:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:440) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:342) ~[java.net.http:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-342.jar:3.3.0-SNAPSHOT (git-c3583e18-b342)]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.net.ConnectException
        at jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1045) ~[java.net.http:?]
        at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:224) ~[java.net.http:?]
        at jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56) ~[java.net.http:?]
        at jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:380) ~[java.net.http:?]
        at jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128) ~[java.net.http:?]
        at jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.establishExchange(Exchange.java:368) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:500) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:405) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:397) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:409) ~[java.net.http:?]
        ... 17 more
Caused by: java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
        at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:842) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:865) ~[?:?]
        at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:208) ~[java.net.http:?]
        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
        at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:210) ~[java.net.http:?]
        at jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56) ~[java.net.http:?]
        at jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:380) ~[java.net.http:?]
        at jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128) ~[java.net.http:?]
        at jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.establishExchange(Exchange.java:368) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:500) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:405) ~[java.net.http:?]
        at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:397) ~[java.net.http:?]
        at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:409) ~[java.net.http:?]
        ... 17 more

An error occurs when I DROP INPUT ports except port 25565 and 22 using iptables.

**Comment by waterghost-2046** [comment]
FORWARD and OUTPUT are both allowed

**Comment by electronicboy** [comment]
> Caused by: java.nio.channels.UnresolvedAddressException

The server needs to talk to mojang for authentication and such, dropping all ports will affect things like DNS if you don't configure it properly

**Comment by FatalMerlin** [comment]
> > Caused by: java.nio.channels.UnresolvedAddressException
> 
> The server needs to talk to mojang for authentication and such, dropping all ports will affect things like DNS if you don't configure it properly

Which INBOUND ports are required for that? I could not find any documentation about which inbound ports Velocity requires beyond the main proxy port, defaulting to 25577.

Can you share any information on this? Disabling my firewall temporarily to troubleshoot this allowed it to work, so clearly it is the culprit, but I need to know which port is required here. Same as described by @waterghost-2046 , OUTBOUND traffic is not blocked, only inbound.

**Comment by FatalMerlin** [comment]
@waterghost-2046 I was missing an inbound firewall rule for DNS traffic. Might be same for you?
