### ISSUE TITLE
Resourcepack issues while connecting to two backends in a row

### ISSUE THREAD

**Issue by smhcnshn** [PaperMC/Velocity#1279]
If we connect to two backend servers that both have their own resourcepack, switching from the first server to a second one, the second backend will have issues loading the resourcepack, it won't even prompt the user, it will just get stuck without doing anything
however connecting to the second backend directly without connecting to the first one enables the pack to load, keep in mind that both servers have their own different packs

**Proxy --> Backend1 (pack loads) --> Backend2 (pack won't load)**

**Proxy --> Backend2 (pack loads)**

I have confirmed this situation only happens while under a velocity proxy.

**Comment by Timongcraft** [comment]
Are the packs loaded using the velocity api or on the backend?

**Comment by Timongcraft** [comment]
And which version of Minecraft are you using?

**Comment by smhcnshn** [comment]
1.19.4 and 1.20.2 and they both are loaded on the backend

**Comment by Timongcraft** [comment]
So the backends have different versions? (and have ViaVersion)
If so have you tried with only one version? (aka without ViaVersion)

**Comment by smhcnshn** [comment]
Sure, i've put them into the same versions and disabled viaversion on both, issue persists, this time console printed this stacktrace out

```
java.io.IOException: Kurulan bir bağlantı, ana makinenizdeki yazılım tarafından iptal edildi
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:284) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:259) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:417) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-82189a6a-b366)]
	at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
```

the line at the top just says that generic kick message forcibly closed something like that

**Comment by electronicboy** [comment]
are you using different UUIDs in the server.properties for the resource packs? You're also using an outdated version

**Comment by smhcnshn** [comment]
They are different, are you talking about the velocity version? I had downgraded it thinking it was an issue with the latest, because i also had the issue with the latest release

**Comment by smhcnshn** [comment]
Also this time it prompted the mojang loading screen, but the bar couldnt complete and restarted the load few times before kicking me with resource reload failed message at the top right on my screen

**Comment by DasBabyPixel** [comment]
I think I ran into the same issue:
I have two resource pack requests with a custom resource pack backend.
I have to send the requests one-by-one (the first is kind of a "probe" to get some player data, the second is the actual resource pack)
The issue is: The client has to complete the first request fully (send a non-intermediate state packet), before velocity even sends the download packet for the second request.
I assume the issue originates in [ModernResourcePackHandler#L177](https://github.com/PaperMC/Velocity/blame/5d450ab3c74ae7ccca13abe2cde20b8473fe64e4/proxy/src/main/java/com/velocitypowered/proxy/connection/player/resourcepack/handler/ModernResourcePackHandler.java#L177).

I need to be able to send a resource pack request to the player while the player is currently downloading another resource pack. I'm gonna do this with reflection for now, hope we get an API at some point. Tbh I'd love to know why resource packs are even queued, #1225 doesn't seem to tell much...

And this happens on the newest velocity version (built from source), just to be clear.

**Comment by electronicboy** [comment]
Does the client support sending multiple resource pack loads while it's already processing them?

**Comment by DasBabyPixel** [comment]
I did some more investigation into this: It supports sending the packets and preparing to download while it is downloading a pack.
But it does not support downloading 2 packs at the same time.

What I do (with hacks, can't do it without rn in velocity):
I start download of a "probe" pack to get client information
When the client connects to the pack server I do not let the download finish yet (server waits with the answer)
Because the client connected to the pack server, I have it's information like pack version etc. and can generate a resourcepack hash.
I send the actual resourcepack packet with the hash to the client.
The client runs its tick loop and accepts the actual resourcepack (state ACCEPTED).
Once the client sends that packet, I complete the probe http request (client sees download finished, but new pack arrived, so it starts the next download instead of reloading resources)
Once the new pack download is complete, the client reloads resources.

Had I not delayed the completion of the pack, then the client would've (likely, it's a race condition) finished the probe download before it received the second request and ran the tick loop to ACCEPT it. Because it would have finished the download, and thought "oh, nothing else to download, lets reload resources" and then the actual resourcepack packet would've been sent and another resource reload would've been required.
