### ISSUE TITLE
Unexpected client disconnection with "Connection reset" error

### ISSUE THREAD

**Issue by TianmuTNT** [PaperMC/Velocity#1287]
Hi Velocity team,

I encountered an issue where a player was suddenly disconnected from my Velocity server with a "Connection reset" error, without any prior signs of network instability. Here's the relevant snippet from the server log:

[11:20:02 INFO]: [connected player] LLL (/xxx:7073) has disconnected: 您的连接发生内部错误。
[11:20:02 ERROR]: [connected player] LLL (/xxx:7073): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@1a9e4e91
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
[11:20:02 INFO]: [server connection] LLL -> main has disconnected

The server's network condition appears to be normal. So far, two players have encountered similar disconnections.

My server environment:
- OS: Windows Server 2019 Datacenter
- Java version: Alibaba Dragonwell JDK 17
- Velocity version: 3.3.0-SNAPSHOT (git-9e42049a-b376)

I'm not quite sure how to diagnose this issue further. I would greatly appreciate any insights or suggestions you might have regarding what could be causing these disconnections and what steps I can take to troubleshoot the problem.

Please let me know if you need any additional information.

Thanks in advance for your help!

**Comment by electronicboy** [comment]
Connection reset means that the TCP socket was closed externally in an unexpected manner, there is generally nothing we can do about this, you'd need to look towards client logs to see if there is any useful information in there, or look into monitoring your network, etc
