### ISSUE TITLE
Disconnect server

### ISSUE THREAD

**Issue by ayide01** [PaperMC/Velocity#1291]
[11:42:01 ERROR]: [connected player] Ay01 (<ip address withheld>): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@23301ce9
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-376.jar:3.3.0-SNAPSHOT (git-9e42049a-b376)]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by electronicboy** [comment]
all we can tell you is what the message says, a TCP connection was closed unexpectedly

For support, please use the forums/discord
