### ISSUE TITLE
plugin is not registered

### ISSUE THREAD

**Issue by Lory9098** [PaperMC/Velocity#1307]
[12:17:01 ERROR]: Can't create plugin neoproxy
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: plugin is not registered
  at NeoProxy.<init>(NeoProxy.java:42)
  at VelocityPluginModule.configure(VelocityPluginModule.java:50)
  while locating NeoProxy

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
NeoProxy:                 "it.neocosmic.neoproxy.NeoProxy"
VelocityPluginModule:     "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:124) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
Caused by: java.lang.IllegalArgumentException: plugin is not registered
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler.buildTask(VelocityScheduler.java:84) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at it.neocosmic.neoproxy.redis.Redis.<init>(Redis.java:20) ~[?:?]
        at it.neocosmic.neoproxy.NeoProxy.<init>(NeoProxy.java:89) ~[?:?]
        at it.neocosmic.neoproxy.NeoProxy$$FastClassByGuice$$69758.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at it.neocosmic.neoproxy.NeoProxy$$FastClassByGuice$$69758.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        ... 6 more

**Comment by electronicboy** [comment]
> at com.velocitypowered.proxy.scheduler.VelocityScheduler.buildTask(VelocityScheduler.java:84) ~[Proxy.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]

You tried to pass in something into thee scheduler while not being loaded, likely doing it during class init or some other place that is too early for your instance to have actually been registered

**Comment by Lory9098** [comment]
ok fixed, if anyone is having the same problem as me they just need to make sure that in the constructor, they assign only the injected variables, and perform the other operations in the ProxyInitializeEvent
