### ISSUE TITLE
java.io.IOException When Connecting to 1.20.4 Server With 1.16.5 Client

### ISSUE THREAD

**Issue by ENDlezZenith** [PaperMC/Velocity#1330]
### My Environment
Proxy Version: Velocity 3.3.0-390
Server Version: 1.20.4+Fabric-0.14.25 with latest Via* plugins
Server Mods: CrossStitch 0.16 + FabricProxy-Lite 0.27
Client Version: Vanilla 1.16.5 and Vanilla 1.18.2 Tested

### Description
Hi, Velocity Team!
I got this error when using low version clients (I've tested 1.16.5 and 1.18.2) to connect to a 1.20 server, is there any idea on this:
```
[01:28:39 ERROR]: [connected player] XXX (/XXX.XXX.XXX.XXX: XXXXX): unable to connect to server XXX
java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:215) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:125) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by electronicboy** [comment]
We do not support protocol hacks, and this is generally not the place for support (the forums/discord are a better place for that)

**Comment by ENDlezZenith** [comment]
> We do not support protocol hacks, and this is generally not the place for support (the forums/discord are a better place for that)

Sorry but what do you mean by "do not support protocol hacks"? Does that mean Via* is not supported here? I was thinking whether this is related to #1251.

**Comment by electronicboy** [comment]
correct, we do not support Via, nor can we generally provide advice around such generic issues on the issue tracker

**Comment by ENDlezZenith** [comment]
> correct, we do not support Via, nor can we generally provide advice around such generic issues on the issue tracker

Ok thanks.

**Comment by ENDlezZenith** [comment]
Okay, seems duplicated with [ViaBackwards#642](https://github.com/ViaVersion/ViaBackwards/issues/642).
