### ISSUE TITLE
CorruptedFrameException: Bad VarInt decoded

### ISSUE THREAD

**Issue by Sander0542** [PaperMC/Velocity#1370]
### Expected Behavior

When I connect to my backend server which is running Valhelsia 6 (Forge 1.20.1) I can connect and start playing.

### Actual Behavior

When I am trying to connect to the backend server I get the following message: `Unable to connect gou to walhelsia6. Please try again later.`

![image](https://github.com/PaperMC/Velocity/assets/11409610/06211405-12d3-40f2-a581-69c77eb5877c)

### Steps to Reproduce

The `ProtocolUtils.readVarInt` method calls the `readVarIntSafely` method, but that returns the `Integer.MIN_VALUE` which is invalid. When I call the same method again it returns a valid Integer. In my case `17`.

https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java#L129-L136

Current implementation:

```java
  public static int readVarInt(ByteBuf buf) {
    int read = readVarIntSafely(buf);
    if (read == Integer.MIN_VALUE) {
      throw MinecraftDecoder.DEBUG ? new CorruptedFrameException("Bad VarInt decoded")
          : BAD_VARINT_CACHED;
    }
    return read;
  }
```

Working implementation:

```java
    public static int readVarInt(ByteBuf buf) {
        int read = readVarIntSafely(buf);
        if (read == Integer.MIN_VALUE) {
            read = readVarIntSafely(buf);
            if (read == Integer.MIN_VALUE) {
                throw MinecraftDecoder.DEBUG ? new CorruptedFrameException("Bad VarInt decoded")
                        : BAD_VARINT_CACHED;
            }
        }
        return read;
    }
```

### Plugin List

https://modrinth.com/plugin/ambassador

### Velocity Version

Velocity 3.3.0-SNAPSHOT (git-aa4e8780-b401)
velocity.command.version-copyright
velocitypowered.com - GitHub

### Additional Information

```log
[20:18:40] [Netty epoll Worker #1/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] Sander0542 -> valhelsia6: exception encountered in org.adde0109.ambassador.velocity.backend.ForgeLoginSessionHandler@e1cc3f2
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.LoginPluginMessagePacket Direction CLIENTBOUND Protocol 1.20 State LOGIN ID 4
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.netty.handler.codec.CorruptedFrameException: Bad VarInt decoded
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readVarInt(ProtocolUtils.java:132) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.protocol.packet.LoginPluginMessagePacket.decode(LoginPluginMessagePacket.java:66) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.3.0-SNAPSHOT-400.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	... 24 more
```

**Comment by electronicboy** [comment]
that working implementation just screams that the proxy is being sent bad (vanilla) data, i can't look right now, but, I'd guess that an earlier packet was malformed or modified in an unsupported manner

**Comment by Sander0542** [comment]
I am running the [proxy-compatible-forge](https://modrinth.com/mod/proxy-compatible-forge) mod in the backend server to enable modern forwarding.

Also, I really don't have any experience using buffers, so the only reason I found this solution was that I was trying to debug it by creating a temp variable. Then I saw the next time I called the function I got 17 as a result. This made my try it and it worked, but I have no clue why.

**Comment by xfyqs** [comment]
why it had been stoped?

**Comment by Lucky-dummy** [comment]
The fix hasn't appeared yet?

**Comment by Sander0542** [comment]
@electronicboy have you been able to take a look at it yet?

**Comment by electronicboy** [comment]
No, I would need a minimal reproduction, otherwise, it's going to take some time for me to get to this as I'm still recovering and getting back into gear from eye surgery

**Comment by Sander0542** [comment]
Thanks for your quick response @electronicboy. I will write up a short guide to reproduce this issue.

I hope you have a speedy recovery!

**Comment by Sander0542** [comment]
## Prerequisites

- Curseforge Launcher

## Steps

### Backend server

1. Download the Server Pack for [Valhelsia 6](https://www.curseforge.com/minecraft/modpacks/valhelsia-6)
2. Unzip the Server Pack to a folder.
3. Set the server to offline mode (server.properties)
4. Download the [Proxy Compatible Forge](https://modrinth.com/mod/proxy-compatible-forge) mod.
5. Add the Proxy Compatible Forge mod to the `mods` folder.
6. Add the forwaringSecret to the config file `config/pcf-common.toml`.
    ```toml
    #Modern Forwarding Settings
    [modernForwarding]
	    forwardingSecret = "secret"
    ```
7. Start the server

### Proxy server (Velocity)

1. Download the latest version of the Velocity server.
2. Download the [Ambassador](https://modrinth.com/plugin/ambassador) plugin.
3. Add the Ambassador mod to the `plugins` folder.
4. Configure the same forwarding secret in velocity (in the guide this would be `secret`).
5. In the `velocity.toml` file change the following entries.
    1. `player-info-forwarding-mode = "modern"`
    2. `announce-forge = true`
    3. `ping-passthrough = "mods"`
    4. Add the backend server to the servers section

### Client

1. Install the [Valhelsia 6](https://www.curseforge.com/minecraft/modpacks/valhelsia-6) client in the CurseForge Launcher.
2. Start the Valhelsia 6 profile
3. Connect to the proxy server.

After following this guide you should be getting the same error as described in this issue.

@electronicboy if you need more information please let me know :)

**Comment by electronicboy** [comment]
by minimal repo I generally mean reducing the number of mods towards a more core collective of them which causes a failure

**Comment by Sander0542** [comment]
I don't have enough experience with Forge mods to know where to start with removing mods and which ones to keep. Is there anyone else who knows how to do this?

**Comment by 456dev** [comment]
found cause in this specific case: everycompat + moonlight lib

on login it sends a plugin message to the client https://github.com/MehVahdJukaar/WoodGood/blob/e71d856801c7cc003b284d35d4816d5954f11fdf/forge/src/main/java/net/mehvahdjukaar/every_compat/forge/EveryCompatForge.java#L169-L176 

everycompat registeres that packet here, as the 2nd packet
https://github.com/MehVahdJukaar/WoodGood/blob/e71d856801c7cc003b284d35d4816d5954f11fdf/common/src/main/java/net/mehvahdjukaar/every_compat/ECNetworking.java#L29

in moonlight's forge impl, this is an int incremented each registered packet
https://github.com/MehVahdJukaar/Moonlight/blob/cb64081582d667d1440841163a6887b55edb20b6/forge/src/main/java/net/mehvahdjukaar/moonlight/api/platform/network/forge/ChannelHandlerImpl.java#L36-L56
so should be 1?

however, it looks as if the encoded "Message ID" is actually Integer.MIN_VALUE, as its not generated by hitting the fall-through case in readVarIntSafely
![image](https://github.com/user-attachments/assets/b4f6e0f8-559a-4ab3-b440-079b8bb78246)

(sidenote, forge seems to use this as a constant across all players, recommending mods to generate this on startup iirc, against what wiki.wg says of being unique per-connection)

even if i dont 100% know the cause, the suggested working impl is not a fix.
it reads the next varint, the length of the channel string, as the id.
in this case 17 for the channel "everycomp:channel"
with this fix applied, it reads the start of the channel name as the size, and the binary packet data as garbage in the channel name.

easy reproduction is to remove every mod except everycompat + pcf, and notice how you cant connect since it say reading some hundreds of characters, instead of the remaining 16 or whatever.

**Comment by electronicboy** [comment]
the curseforge client is seemingly breaking any form of java I pass into it, requiring me to reinstall it...
I'd guess, we're actually being passed MIN_VALUE here, but, I have no means to really test it; so, all I can assume is that reading the min_value and accepting it as the ID is the answer here

**Comment by Sander0542** [comment]
When looking at the source code you send, I found out that I could disable whether the mod checks the packet. By set the `mod_version_check_packet` to `false` in the `config/everycomp-common.toml` file, you can successfully connect without any hacky workarounds.

```toml filename="config/everycomp-common.toml"
#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
mod_version_check_packet = false
```
