### ISSUE TITLE
Can't build drom sources

### ISSUE THREAD

**Issue by La1m1e** [PaperMC/Velocity#1407]
### Expected Behavior

Can build from sources

### Actual Behavior

```
An exception occurred applying plugin request [id: 'velocity-init-manifest']
> Failed to apply plugin 'velocity-init-manifest'.
   > Process 'command 'git'' finished with non-zero exit value 128

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'velocity-init-manifest']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:179)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$400(DefaultPluginRequestApplicator.java:52)
```

### Steps to Reproduce

Try to build

### Plugin List

-

### Velocity Version

-

**Comment by electronicboy** [comment]
The thing expects to be running as a cloned git repository, outside of that, env specific build breakages are something you'd need to diagnose
