### ISSUE TITLE
Exception encountered in Client Play Session Handler

### ISSUE THREAD

**Issue by mystame** [PaperMC/Velocity#1437]
### Expected Behavior

players to not get kicked

### Actual Behavior

Players are being kicked from server randomly

### Steps to Reproduce

Seems to happen at random, sometimes affecting one person, other times a group of people

### Plugin List

Plugins: advancedportals, floodgate, geyser, logger-velocity, luckperms, mapmodcompanion, papiproxybridge, plan, reconnect, vpacketevents, signedvelocity, spark, velocity_chat, velocitywhitelist, voicechat

### Velocity Version

Velocity 3.3.0-SNAPSHOT (git-00ed2284-b415)

### Additional Information

[04:18:19] [Netty NIO Worker #1/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] <player> (/IP:port) has disconnected: An internal error occurred in your connection.
[04:18:19] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] <player> (/IP:port): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@444b3da6
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[04:18:19] [Netty NIO Worker #1/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] <player> -> Druidia has disconnected
[04:18:19] [Velocity Async Event Executor - #2/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: §8[§c-§8]§r <player> §2left the proxy

**Comment by electronicboy** [comment]
connection reset means that the TCP connection was closed externally, you would need to look into client logs, etc, for more information
