### ISSUE TITLE
Exception in thread "SIGCONT handler"

### ISSUE THREAD

**Issue by DominicTWHV** [PaperMC/Velocity#1439]
### Expected Behavior

Running normally

### Actual Behavior

Random crashes

### Steps to Reproduce

Letting the proxy run.

Config:

```
# Config version. Do not change this
config-version = "2.7"

# What port should the proxy be bound to? By default, we'll bind to all addresses on port 25565.
bind = "0.0.0.0:25565"

# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "Another Minecraft Server"

# What should we display for the maximum number of players? (Velocity does not support a cap
# on the number of players online.)
show-max-players = 20

# Should we authenticate players with Mojang? By default, this is on.
online-mode = true

# Should the proxy enforce the new public key security standard? By default, this is on.
force-key-authentication = true

# If client's ISP/AS sent from this proxy is different from the one from Mojang's
# authentication server, the player is kicked. This disallows some VPN and proxy
# connections but is a weak form of protection.
prevent-client-proxy-connections = false

# Should we forward IP addresses and other data to backend servers?
# Available options:
# - "none":        No forwarding will be done. All players will appear to be connecting
#                  from the proxy and will have offline-mode UUIDs.
# - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
#                  if you run servers using Minecraft 1.12 or lower.
# - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
#                  unable to implement network level firewalling (on a shared host).
# - "modern":      Forward player IPs and UUIDs as part of the login process using
#                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "modern"

# If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
# The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"

# Announce whether or not your server supports Forge. If you run a modded server, we
# suggest turning this on.
# 
# If your network runs one modpack consistently, consider using ping-passthrough = "mods"
# instead for a nicer display in the server list.
announce-forge = false

# If enabled (default is false) and the proxy is in online mode, Velocity will kick
# any existing player who is online if a duplicate connection attempt is made.
kick-existing-players = false

# Should Velocity pass server list ping requests to a backend server?
# Available options:
# - "disabled":    No pass-through will be done. The velocity.toml and server-icon.png
#                  will determine the initial server list ping response.
# - "mods":        Passes only the mod list from your backend server into the response.
#                  The first server in your try list (or forced host) with a mod list will be
#                  used. If no backend servers can be contacted, Velocity won't display any
#                  mod information.
# - "description": Uses the description and mod list from the backend server. The first
#                  server in the try (or forced host) list that responds is used for the
#                  description and mod list.
# - "all":         Uses the backend server's response as the proxy response. The Velocity
#                  configuration is used if no servers could be contacted.
ping-passthrough = "all"

# If not enabled (default is true) player IP addresses will be replaced by <ip address withheld> in logs
enable-player-address-logging = true

[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
survival = "[REDACTED]:25567"
maintenance = "[REDACTED]:25569"
develop = "[REDACTED]:25568"
# In what order we should try servers when a player logs in or is kicked from a server.
try = [
    "survival",
    "maintenance",
    "develop"
]

[forced-hosts]
# Configure your forced hosts here.
"[REDACTED]" = [
    "survival",
    "maintenance",
    "develop"
]

[advanced]
# How large a Minecraft packet has to be before we compress it. Setting this to zero will
# compress all packets, and setting it to -1 will disable compression entirely.
compression-threshold = 128

# How much compression should be done (from 0-9). The default is -1, which uses the
# default level of 6.
compression-level = -1

# How fast (in milliseconds) are clients allowed to connect after the last connection? By
# default, this is three seconds. Disable this by setting this to 0.
login-ratelimit = 5000

# Specify a custom timeout for connection timeouts here. The default is five seconds.
connection-timeout = 8000

# Specify a read timeout for connections here. The default is 30 seconds.
read-timeout = 30000

# Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
# don't enable it.
haproxy-protocol = false

# Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
tcp-fast-open = true

# Enables BungeeCord plugin messaging channel support on Velocity.
bungee-plugin-message-channel = false

# Shows ping requests to the proxy from clients.
show-ping-requests = true

# By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
# loses connection to the server without an explicit disconnect message by attempting to fall the
# user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
# can disable this setting to use the BungeeCord behavior.
failover-on-unexpected-server-disconnect = true

# Declares the proxy commands to 1.13+ clients.
announce-proxy-commands = true

# Enables the logging of commands
log-command-executions = true

# Enables logging of player connections when connecting to the proxy, switching servers
# and disconnecting from the proxy.
log-player-connections = true

# Allows players transferred from other hosts via the
# Transfer packet (Minecraft 1.20.5) to be received.
accepts-transfers = false

[query]
# Whether to enable responding to GameSpy 4 query responses or not.
enabled = false

# If query is enabled, on what port should the query protocol listen on?
port = 25565

# This is the map name that is reported to the query services.
map = "Default"

# Whether plugins should be shown in query response by default or not
show-plugins = false
```

Host OS: Ubuntu Server 2204 LTS

Proxy works as expected, until it crashes out of nowhere. It's a rare issue, first time seeing this crash after a month, however no recent changes to backend/proxy were made.

### Plugin List

SVC (latest), backend is Fabric 1.21 with FabricProxyLite (Latest)

Anti Server Scanner (not plugin, but bash cronjob): https://github.com/DominicTWHV/Anti_Server_Scanner , been running for a few days, so shouldn't cause issues. This does not directly interfere with Velocity anyways.

### Velocity Version

Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)

```
velocity info
[05:53:20 INFO]: Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)
[05:53:20 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[05:53:20 INFO]: velocitypowered.com - GitHub
```

### Additional Information

Logs:

(Normal operation, until it crashed)

```
[16:00:09] [Shutdown thread/INFO] [com.velocitypowered.proxy.VelocityServer]: Shutting down the proxy...
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Exception in thread "SIGCONT handler" Exception in thread "SIGCONT handler" java.io.IOError: java.io.IOException: Error calling ioctl(TIOCGWINSZ): return code is -1
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:63)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:231)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:1160)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:90)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:66)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.utils.Signals.lambda$register$1(Signals.java:52)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at jdk.proxy2/jdk.proxy2.$Proxy31.handle(Unknown Source)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:218)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.io.IOException: Error calling ioctl(TIOCGWINSZ): return code is -1
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.jansi.JansiNativePty.getSize(JansiNativePty.java:154)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:61)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 9 more
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.io.IOError: java.io.IOException: Error calling ioctl(TIOCGWINSZ): return code is -1
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:63)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:231)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:1160)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:90)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:66)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.utils.Signals.lambda$register$1(Signals.java:52)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at jdk.proxy2/jdk.proxy2.$Proxy31.handle(Unknown Source)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:218)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.io.IOException: Error calling ioctl(TIOCGWINSZ): return code is -1
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.jansi.JansiNativePty.getSize(JansiNativePty.java:154)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:61)
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 9 more
[16:00:09] [Shutdown thread/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Closing endpoint /0.0.0.0:25565
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Exception in thread "main" java.io.IOError: java.io.IOException: Input/output error
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.Velocity.main(Velocity.java:77)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.io.IOException: Input/output error
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.io.FileInputStream.read0(Native Method)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.io.FileInputStream.read(FileInputStream.java:231)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:81)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:157)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:56)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 9 more
```

**Comment by DominicTWHV** [comment]
Java version:

```
dominic@velocity:~$ java -version
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

**Comment by electronicboy** [comment]
```
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.io.IOException: Error calling ioctl(TIOCGWINSZ): return code is -1
[16:00:09] [SIGCONT handler/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.jline.terminal.impl.jansi.JansiNativePty.getSize(JansiNativePty.java:154)
```

```
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.io.IOException: Input/output error
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.io.FileInputStream.read0(Native Method)
[16:00:09] [main/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.io.FileInputStream.read(FileInputStream.java:231)
```

Looks like the environment that the server was running in broke/died and the server was taken down with it. SIGCONT is an external OS signal which suggests that your environment has something weird going on with it

**Comment by DominicTWHV** [comment]
Interesting, any potential solutions that I can try?

**Comment by electronicboy** [comment]
I have no idea what is inducing your issue

**Comment by DominicTWHV** [comment]
Using GNU screen to keep the session alive if that matters. Honestly I’m also pretty stumped, will try updating packages and see if it crashes again.

**Comment by DominicTWHV** [comment]
Updated packages, so far no crashes. Will close this issue for now and see how it runs. Thanks for the heads up.
