### ISSUE TITLE
Can't join an ATM10 server (mc 1.21.1) on Snapshot 436

### ISSUE THREAD

**Issue by PedroPF1234** [PaperMC/Velocity#1440]
### Expected Behavior

I expected to get a simple connection like the one I get connecting with ATM8 (mc version 1.19.2). Both backend servers are running the [PCF](https://github.com/adde0109/Proxy-Compatible-Forge/tree/1.1.5) mod and both have the forwarding secret set up.

### Actual Behavior

When I try to connect, I get this log on my velocity terminal:
```
[19:49:27 INFO]: [connected player] _PedroPF_ (/<my_ip>:54558) has connected
[19:49:27 INFO]: [server connection] _PedroPF_ -> atm10 has connected
[19:49:27 ERROR]: [server connection] _PedroPF_ -> atm10: exception encountered in com.velocitypowered.proxy.connection.backend.ConfigSessionHandler@7ed227b6
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.config.KnownPacksPacket Direction CLIENTBOUND Protocol 1.21 State CONFIG ID e
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.velocitypowered.proxy.util.except.QuietDecoderException: too many known packs
[19:49:27 INFO]: [server connection] _PedroPF_ -> atm10 has disconnected
[19:49:27 ERROR]: [connected player] _PedroPF_ (/<my_ip>:54558): unable to connect to server atm10
java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.disconnected(ConfigSessionHandler.java:335) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:126) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueOutboundHandler.channelInactive(PlayPacketQueueOutboundHandler.java:79) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueInboundHandler.channelInactive(PlayPacketQueueInboundHandler.java:75) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[19:49:27 INFO]: [connected player] _PedroPF_ (/<my_ip>:54558) has disconnected: Unable to connect you to atm10. Please try again later.
```

And I get the following on the server's terminal:
```
[19:49:27] [Server thread/INFO] [minecraft/ServerConfigurationPacketListenerImpl]: com.mojang.authlib.GameProfile@606e9bed[id=f4e232a5-7a1e-40b7-b3c5-4adf71f988f1,name=_PedroPF_,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcyNzgwODU2NjcxMywKICAicHJvZmlsZUlkIiA6ICJmNGUyMzJhNTdhMWU0MGI3YjNjNTRhZGY3MWY5ODhmMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJfUGVkcm9QRl8iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk5NjkzMmEyODE2ZjI0MjQyMzM1ZDE2Y2M4MDRjMjU1MDgxM2NhNWFkYzk1YTUyMGQ2MGNlOGMwN2EzOWU5YSIKICAgIH0KICB9Cn0=, signature=DEJUDSEb+SQRf0fGsmMdJnQD/lOzmUGHSlO89VWt0HtUNeVxqBCvhUdmfBzDrsf5pOyzMbB8pdGBcfRIdiD3M1m3/yJXrEafTuQiOSYTs+XlwYVLwkQqeQbDgJjIlouBX2J3qVkSNpVZ4XO/SMQ2xOU4Fo7bV3lzTm1xyAzmUnrzQmhF0cZDFSuAzkLGvdiqFaj4GAMtkrSrEQJjuJcpa2a6Jxr6XYS/ff6zN+2j6eNsoige286MV57XV3Zok9h/gqJ8ZejF0QhxRzJgJjHzLAd6jRJwinrhYdRN1lBubK90J8MNeEV5X9xj2d0vztmYVvTapNGgbr1VhtEEwc1uiIjCDLWFuJWVlH+J246UPqxmQ0nmc2su6G8UuPGwKXd88rnPHZWHKgFykPOBD0NhXwR4OBUAl22QhM01SSf5T5kq7TL5SJZR/oW36GeBqgVnk9BRm2PRfCk3UtI3jWi57FborYk6YkMvjQ3LnBN2AZJMx+Iu3BHNyrosLAnRKMfUUPm25NfAAkUY0mwkJMH0UP8EekntMOibPha/yFxEI8H9eyyNoN0VC5YLyCPAm2qZoFfHTiPubo435Mty5V0VPM32kSvmy5Cc8COVxRtc/Pg8j5gListzDZ8p28LOaBeYVD4OUBebhllnX91gQZhArJTJl7wLNoqPD5DFO+8HSJc=]]}] lost connection: Disconnected
```

### Steps to Reproduce

To obtain the exact logs I initialized velocity with the following command:

```bash
java -Xms512M -Xmx1G -Dvelocity.packet-decode-logging=true -jar velocity-3.3.0-436.jar
```

I should also note that, before running this command, I simply ran:
```bash
java -Xms512M -Xmx1G -jar velocity-3.3.0-436.jar
```

This one produced a similar log but between the "connected" and "disconnected" lines, the output was much shorter:
```
[21:09:16 INFO]: [server connection] _PedroPF_ -> atm10 has connected
[21:09:16 ERROR]: [server connection] _PedroPF_ -> atm10: exception encountered in com.velocitypowered.proxy.connection.backend.ConfigSessionHandler@4c6ef64d
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). For more information, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
[21:09:16 INFO]: [server connection] _PedroPF_ -> atm10 has disconnected
```

### Plugin List

 Ambassador-Velocity-1.4.4-all.jar; ViaBackwards-5.0.3.jar; ViaRewind-4.0.2.jar;  ViaVersion-5.0.3.jar

### Velocity Version

 Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)

### Additional Information

 Running Ubuntu 22.04.5 LTS as OS.
Unlike ATM8, ATM10 uses neoforge. My servers are running ATM8 v1.1.0 and ATM10 v0.40.0.

**Comment by PedroPF1234** [comment]
The answer was given in discord:
```
That mod is defining more 'known packs' that vanilla permits, you can change the limit with -Dvelocity.max-known-packs=XX, default is 64
```
After setting the max-know-packs to a higher number, it connected. I incremented the default value until it could connect.

**Comment by LilyKensa** [comment]
I encountered the same issue when using a fabric backend server with Fabric Proxy Lite mod

Setting `max-known-packs` to `128` solved the disconnecting issue :)
