### ISSUE TITLE
When trying to connect via to a Fabric server in gives an error

### ISSUE THREAD

**Issue by RJSkylanderboy** [PaperMC/Velocity#1443]
### Expected Behavior

Connect to Fabric server

### Actual Behavior

exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@33079afe
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol 1.21 State PLAY ID 11
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
	at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:89) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.deserializeNode(AvailableCommandsPacket.java:210) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:88) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT (git-99aaf3ce-b439)]
	... 28 more

### Steps to Reproduce

Log on to the Fabric server with the modded client

### Plugin List

Default

### Velocity Version

3.4.0-SNAPSHOT (git-99aaf3ce-b439)

**Comment by Legomountain14** [comment]
I am getting a similar error

**Comment by electronicboy** [comment]
https://docs.papermc.io/velocity/server-compatibility#fabric
