### ISSUE TITLE
Player closes client with error message

### ISSUE THREAD

**Issue by 7hehehe** [PaperMC/Velocity#1456]
### Expected Behavior

[10:13:30 ERROR]: [connected player] BlockESP (<ip address withheld>): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@6cca765a
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:356) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]

### Actual Behavior

The player closes the client within the server

### Steps to Reproduce

The player closes the client within the server

### Plugin List

pxVelocity
pxQueue-Velocity

https://refinedev.xyz/resources/phoenix.3/

### Velocity Version

> velocity info
[11:55:44 INFO]: Velocity 3.4.0-SNAPSHOT (git-08a42b37-b449)
[11:55:44 INFO]: Copyright 2018-2023 Velocity Contributors。Velocity 以 GNU 通用公共许可证第三版授权。
[11:55:44 INFO]: PaperMC - GitHub

**Comment by codebycam** [comment]
Hello, your error just means the TCP connection was reset and it's most likely due to the plugins you're running on your proxy and not a direct bug with Velocity, which is what this issue tracker is for. For general support you can join our [Discord](https://discord.com/invite/papermc) or post on the [forums](https://forums.papermc.io/).
