### ISSUE TITLE
A packet did not decode successfully (invalid data)

### ISSUE THREAD

**Issue by iUnstable0** [PaperMC/Velocity#1472]
### Expected Behavior

I expect it to properly work

### Actual Behavior

I get this error when I try to join my fabric modded server

```
container@pterodactyl~ Server marked as running...
[21:05:58 INFO] [geyser]: Started Geyser on UDP port 19132
[21:05:59 INFO] [geyser]: Done (12.395s)! Run /geyser help for help!
[21:08:12 INFO]: [server connection] iUnstable0 -> survival-modded has connected
[21:08:14 ERROR]: [server connection] iUnstable0 -> survival-modded: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@6f0b7e7
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol 1.21 State PLAY ID 11
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
        at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:89) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.deserializeNode(AvailableCommandsPacket.java:210) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:88) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        ... 30 more
[21:08:14 INFO]: [connected player] iUnstable0 (/10.1.0.123:60277) has disconnected: Your connection to survival-modded encountered a problem.
[21:08:14 INFO]: [server connection] iUnstable0 -> survival-modded has disconnected
```

I am using Fabric loader 0.16.9 (1.21.1 mc version) prism launcher

### Steps to Reproduce

I get the error when I try to join and i get disconnected

this is my velocity config

```
# Config version. Do not change this
config-version = "2.7"
# What port should the proxy be bound to? By default, we'll bind to all addresses on port 25577.
bind = "0.0.0.0:25565"
# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "<#09add3>A Minecraft Server"
# What should we display for the maximum number of players? (Velocity does not support a cap
# on the number of players online.)
show-max-players = 20
# Should we authenticate players with Mojang? By default, this is on.
online-mode = true
# Should the proxy enforce the new public key security standard? By default, this is on.
force-key-authentication = true
# If client's ISP/AS sent from this proxy is different from the one from Mojang's
# authentication server, the player is kicked. This disallows some VPN and proxy
# connections but is a weak form of protection.
prevent-client-proxy-connections = false
# Should we forward IP addresses and other data to backend servers?
# Available options:
# - "none":        No forwarding will be done. All players will appear to be connecting
#                  from the proxy and will have offline-mode UUIDs.
# - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
#                  if you run servers using Minecraft 1.12 or lower.
# - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
#                  unable to implement network level firewalling (on a shared host).
# - "modern":      Forward player IPs and UUIDs as part of the login process using
#                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "modern"
# If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
# The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"
# Announce whether or not your server supports Forge. If you run a modded server, we
# suggest turning this on.
# 
# If your network runs one modpack consistently, consider using ping-passthrough = "mods"
# instead for a nicer display in the server list.
announce-forge = false
# If enabled (default is false) and the proxy is in online mode, Velocity will kick
# any existing player who is online if a duplicate connection attempt is made.
kick-existing-players = false
# Should Velocity pass server list ping requests to a backend server?
# Available options:
# - "disabled":    No pass-through will be done. The velocity.toml and server-icon.png
#                  will determine the initial server list ping response.
# - "mods":        Passes only the mod list from your backend server into the response.
#                  The first server in your try list (or forced host) with a mod list will be
#                  used. If no backend servers can be contacted, Velocity won't display any
#                  mod information.
# - "description": Uses the description and mod list from the backend server. The first
#                  server in the try (or forced host) list that responds is used for the
#                  description and mod list.
# - "all":         Uses the backend server's response as the proxy response. The Velocity
#                  configuration is used if no servers could be contacted.
ping-passthrough = "DISABLED"
# If not enabled (default is true) player IP addresses will be replaced by <ip address withheld> in logs
enable-player-address-logging = true

[servers]
	# Configure your servers here. Each key represents the server's name, and the value
	# represents the IP address of the server to connect to.
	survival = "172.18.0.1:30001"
    survival-modded = '172.18.0.1:30002'
	# In what order we should try servers when a player logs in or is kicked from a server.
	try = ["survival-modded"]
    #try = ["survival"]
	#factions = "172.18.0.1:30067"
[forced-hosts]
	# "redacted" = ["survival"]
    "redacted" = ["survival"]
    "redacted-for-privacy" = ["survival-modded"]
[advanced]
	# Specify a read timeout for connections here. The default is 30 seconds.
	read-timeout = 30000
	# Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
	tcp-fast-open = true
	# How much compression should be done (from 0-9). The default is -1, which uses the
	# default level of 6.
	compression-level = -1
	# How large a Minecraft packet has to be before we compress it. Setting this to zero will
	# compress all packets, and setting it to -1 will disable compression entirely.
	compression-threshold = 256
	# How fast (in milliseconds) are clients allowed to connect after the last connection? By
	# default, this is three seconds. Disable this by setting this to 0.
	login-ratelimit = 3000
	# Specify a custom timeout for connection timeouts here. The default is five seconds.
	connection-timeout = 5000
	# Enables logging of player connections when connecting to the proxy, switching servers
	# and disconnecting from the proxy.
	log-player-connections = true
	# Enables BungeeCord plugin messaging channel support on Velocity.
	bungee-plugin-message-channel = true
	# Shows ping requests to the proxy from clients.
	show-ping-requests = false
	#Allows players transferred from other hosts via the
	#Transfer packet (Minecraft 1.20.5) to be received.
	accepts-transfers = false
	# By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
	# loses connection to the server without an explicit disconnect message by attempting to fall the
	# user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
	# can disable this setting to use the BungeeCord behavior.
	failover-on-unexpected-server-disconnect = true
	# Declares the proxy commands to 1.13+ clients.
	announce-proxy-commands = true
	# Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
	# don't enable it.
	haproxy-protocol = false
	# Enables the logging of commands
	log-command-executions = false
[query]
	# If query is enabled, on what port should the query protocol listen on?
	port = 25577
	# Whether plugins should be shown in query response by default or not
	show-plugins = false
	# This is the map name that is reported to the query services.
	map = "Velocity"
	# Whether to enable responding to GameSpy 4 query responses or not.
	enabled = false

```

### Plugin List

Velocity plugins
```
>....[21:15:34 INFO]: Plugins: velocity, floodgate, geyser, geyserskinmanager-velocity, limboapi, limboreconnect
```

backend mods

```
[21:06:11] [main/INFO]: Loading 164 mods:
        - airhop 21.1.0
        - appleskin 3.0.6+mc1.21
        - armorstatues 21.1.0
           \-- statuemenus 21.1.0
        - barteringstation 21.1.0
        - betterdeserttemples 1.21.1-Fabric-4.1.2
           \-- org_reflections_reflections 0.10.2
        - betterdungeons 1.21.1-Fabric-5.1.4
           \-- org_reflections_reflections 0.10.2
        - betterendisland 1.21.1-Fabric-3.1.1
           \-- org_reflections_reflections 0.10.2
        - betterfortresses 1.21.1-Fabric-3.1.3
           \-- org_reflections_reflections 0.10.2
        - betterjungletemples 1.21.1-Fabric-3.1.2
           \-- org_reflections_reflections 0.10.2
        - bettermineshafts 1.21.1-Fabric-5.1.1
           \-- org_reflections_reflections 0.10.2
        - betteroceanmonuments 1.21.1-Fabric-4.1.2
           \-- org_reflections_reflections 0.10.2
        - betterstrongholds 1.21.1-Fabric-5.1.2
           \-- org_reflections_reflections 0.10.2
        - bettertridents 21.1.0
        - betterwitchhuts 1.21.1-Fabric-4.1.1
           \-- org_reflections_reflections 0.10.2
        - biomesoplenty 21.1.0.7
        - blockrunner 21.1.0
           \-- neoforgedatapackextensions 21.1.0
        - c2me 0.3.0+alpha.0.306+1.21.1
           |-- c2me-base 0.3.0+alpha.0.306+1.21.1
           |-- c2me-client-uncapvd 0.3.0+alpha.0.306+1.21.1
           |-- c2me-fixes-chunkio-threading-issues 0.3.0+alpha.0.306+1.21.1
           |-- c2me-fixes-general-threading-issues 0.3.0+alpha.0.306+1.21.1
           |-- c2me-fixes-worldgen-threading-issues 0.3.0+alpha.0.306+1.21.1
           |-- c2me-fixes-worldgen-vanilla-bugs 0.3.0+alpha.0.306+1.21.1
           |-- c2me-notickvd 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-allocs 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-chunk-access 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-chunkio 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-dfc 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-math 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-scheduling 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-worldgen-general 0.3.0+alpha.0.306+1.21.1
           |-- c2me-opts-worldgen-vanilla 0.3.0+alpha.0.306+1.21.1
           |-- c2me-rewrites-chunk-serializer 0.3.0+alpha.0.306+1.21.1
           |-- c2me-rewrites-chunk-system 0.3.0+alpha.0.306+1.21.1
           |-- c2me-rewrites-chunkio 0.3.0+alpha.0.306+1.21.1
           |-- c2me-server-utils 0.3.0+alpha.0.306+1.21.1
           |-- c2me-threading-lighting 0.3.0+alpha.0.306+1.21.1
           |-- com_ibm_async_asyncutil 0.1.0
           |-- io_reactivex_rxjava3_rxjava 3.1.8
           |-- mixinsquared 0.2.0-beta.6
           |-- net_objecthunter_exp4j 0.4.8
           |-- org_jctools_jctools-core 4.0.5
           \-- org_reactivestreams_reactive-streams 1.0.4
        - cloth-config 15.0.140
           \-- cloth-basic-math 0.6.1
        - comforts 9.0.3+1.21.1
           |-- cardinal-components-base 6.1.0
           |-- cardinal-components-entity 6.1.0
           \-- spectrelib 0.17.2+1.21
                |-- com_electronwill_night-config_core 3.8.0
                \-- com_electronwill_night-config_toml 3.8.0
        - cristellib 1.2.8
           \-- blue_endless_jankson 1.2.3
        - debugify 1.21.1+1.0
        - easyanvils 21.1.0
        - easymagic 21.1.0
        - echochest 21.1.0
        - fabric-api 0.110.0+1.21.1
           |-- fabric-api-base 0.4.42+6573ed8c19
           |-- fabric-api-lookup-api-v1 1.6.70+b559734419
           |-- fabric-biome-api-v1 13.0.30+be1ed2d719
           |-- fabric-block-api-v1 1.0.22+0af3f5a719
           |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
           |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
           |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
           |-- fabric-command-api-v1 1.2.49+f71b366f19
           |-- fabric-command-api-v2 2.2.28+6ced4dd919
           |-- fabric-commands-v0 0.2.66+df3654b319
           |-- fabric-content-registries-v0 8.0.18+b559734419
           |-- fabric-convention-tags-v1 2.1.2+7f945d5b19
           |-- fabric-convention-tags-v2 2.9.2+e60e56d419
           |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
           |-- fabric-data-attachment-api-v1 1.4.0+da19b51a19
           |-- fabric-data-generation-api-v1 20.2.24+16c4ae2519
           |-- fabric-dimensions-v1 4.0.0+6fc22b9919
           |-- fabric-entity-events-v1 1.7.0+2122d82819
           |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
           |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
           |-- fabric-item-api-v1 11.1.1+d5debaed19
           |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
           |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
           |-- fabric-keybindings-v0 0.2.45+df3654b319
           |-- fabric-lifecycle-events-v1 2.5.0+01d9a51c19
           |-- fabric-loot-api-v2 3.0.15+3f89f5a519
           |-- fabric-loot-api-v3 1.0.3+3f89f5a519
           |-- fabric-message-api-v1 6.0.13+6573ed8c19
           |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
           |-- fabric-networking-api-v1 4.3.0+c7469b2119
           |-- fabric-object-builder-api-v1 15.2.1+40875a9319
           |-- fabric-particles-v1 4.0.2+6573ed8c19
           |-- fabric-recipe-api-v1 5.0.13+6508971219
           |-- fabric-registry-sync-v0 5.2.0+34f5d91419
           |-- fabric-renderer-api-v1 3.4.0+c705a49c19
           |-- fabric-renderer-indigo 1.7.0+c705a49c19
           |-- fabric-renderer-registries-v1 3.2.68+df3654b319
           |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
           |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
           |-- fabric-rendering-v0 1.1.71+df3654b319
           |-- fabric-rendering-v1 5.0.5+df16efd019
           |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
           |-- fabric-resource-loader-v0 1.3.1+5b5275af19
           |-- fabric-screen-api-v1 2.0.25+8b68f1c719
           |-- fabric-screen-handler-api-v1 1.3.88+b559734419
           |-- fabric-sound-api-v1 1.0.23+6573ed8c19
           |-- fabric-transfer-api-v1 5.4.2+95bead5f19
           \-- fabric-transitive-access-wideners-v1 6.2.0+45b9699719
        - fabricloader 0.16.9
        - fabricproxy-lite 2.9.0
           \-- com_moandjiezana_toml_toml4j 0.7.2
        - farmersdelight 1.21.1-2.2.7+refabricated
           |-- mm 2.3
           |-- porting_lib_base 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- com_electronwill_night-config_core 3.8.0
           |    |-- com_electronwill_night-config_toml 3.8.0
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- mm 2.3
           |    |-- porting_lib_accessors 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_asm 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_attributes 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_blocks 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_common 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_entity 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_extensions 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_fluids 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_gui_utils 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_level_events 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_mixin_extensions 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_tags 3.0
           |    \-- porting_lib_transfer 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_config 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- com_electronwill_night-config_core 3.8.0
           |    |-- com_electronwill_night-config_toml 3.8.0
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_item_abilities 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_blocks 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_level_events 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_lazy_registration 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_loot 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_conditions 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           \-- porting_lib_recipe_book_categories 3.1.0-beta.47.hotfix.1+1.21.1
                |-- mixinextras 0.5.0-beta.3
                |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
                \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
        - ferritecore 7.0.2-hotfix
        - forgeconfigapiport 21.1.3
           |-- com_electronwill_night-config_core 3.8.0
           \-- com_electronwill_night-config_toml 3.8.0
        - glitchcore 2.1.0.0
           \-- net_jodah_typetools 0.6.3
        - hangglider 21.1.0
        - java 21
        - lithium 0.14.3-snapshot+mc1.21.1-build.92
        - minecraft 1.21.1
        - mr_vanilla_fireflies 3.1
        - pickupnotifier 21.1.0
        - plentyplates 21.1.0
        - portablehole 21.1.0
        - puzzleslib 21.1.22
        - scalablelux 0.1.0+fabric.26c6e72
        - sereneseasons 10.1.0.1
           \-- net_jodah_typetools 0.6.3
        - stoneworks 21.1.0
        - t_and_t 1.13.2
        - tectonic 2.4.1a
        - terrablender 4.1.0.5
        - terralith 2.5.7
        - toughasnails 10.1.0.13
           \-- net_jodah_typetools 0.6.3
        - tradingpost 21.1.0
        - travelersbackpack 10.1.3
        - treechop 0.19.2
        - universalbonemeal 21.1.0
        - visualworkbench 21.1.0
        - xaerominimap 24.6.1
        - yet_another_config_lib_v3 3.6.2+1.21-fabric
           |-- com_twelvemonkeys_common_common-image 3.12.0
           |-- com_twelvemonkeys_common_common-io 3.12.0
           |-- com_twelvemonkeys_common_common-lang 3.12.0
           |-- com_twelvemonkeys_imageio_imageio-core 3.12.0
           |-- com_twelvemonkeys_imageio_imageio-metadata 3.12.0
           |-- com_twelvemonkeys_imageio_imageio-webp 3.12.0
           |-- org_quiltmc_parsers_gson 0.2.1
           \-- org_quiltmc_parsers_json 0.2.1
        - yungsapi 1.21.1-Fabric-5.1.3
           |-- org_javassist_javassist 3.29.2-GA
           \-- org_reflections_reflections 0.10.2
        - yungsbridges 1.21.1-Fabric-5.1.1
           \-- org_reflections_reflections 0.10.2
        - yungsextras 1.21.1-Fabric-5.1.1
           \-- org_reflections_reflections 0.10.2
```

### Velocity Version

```
>....[21:16:12 INFO]: Velocity 3.4.0-SNAPSHOT (git-965db127-b454)
[21:16:12 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[21:16:12 INFO]: PaperMC - GitHub
```

### Additional Information

You see i have floodgate and geyser, but that is for my normal survival backend that is running paperMC and velocity works fine

I have another backend for fabric mods with no floodgate and geyser but it is not working it gives me error Invalid data tbingy, I can connect directly to the fabric server but not through the proxy

This is the link to the zip file for prism launcher
https://drive.proton.me/urls/71G43JJ7RC#OLD5Q38Pc9q1

Link to the mods on the server (Fabric 0.16.9 Minecraft version 1.21.1)
https://drive.proton.me/urls/JCRDM9XE1C#QvH6zfBvBGp2

**Comment by Timongcraft** [comment]
You need [CrossStich](https://modrinth.com/mod/crossstitch), the error is because a mod registered a custom command argument which Velocity can't know. For more information read [the docs](https://docs.papermc.io/velocity/server-compatibility#modded-setups)

**Comment by iUnstable0** [comment]
I cannot install crossSticht becayse it doesnt work on 1.21.1 :(

**Comment by Timongcraft** [comment]
wdym with it doesn't work?

**Comment by iUnstable0** [comment]
it crashes my backend server when i load it because it's only supported for 1.20 and i am on 1.21.1 :(

**Comment by electronicboy** [comment]
Velocity cannot decode arbitrary data it doesn't understand; you'll need to work out why CrossStitch isn't working in your setup

**Comment by iUnstable0** [comment]
crossstitch isnt working because it's not updated for 1.21.1

will crossstitch ever be updated? :(

**Comment by electronicboy** [comment]
it works perfectly fine for others

**Comment by maakiopus** [comment]
Hi i have the same error with crossstitch-0.1.6.jar being already installed any workarounds?
