### ISSUE TITLE
IllegalReferenceCountException on player join

### ISSUE THREAD

**Issue by PhilCCMG** [PaperMC/Velocity#402]
**Velocity Version:** 1.1.2
**Plugins:** None

Whenever players join our proxy, we see this error in console, which prevents the player from joining (Your connection to <server> encountered an error):
```
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:1.1.2]
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[velocity.jar:1.1.2]
  at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[velocity.jar:1.1.2]
  at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[velocity.jar:1.1.2]
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity.jar:1.1.2]
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:1.1.2]
  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity.jar:1.1.2]
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:1.1.2]
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:1.1.2]
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:1.1.2]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
  at com.velocitypowered.proxy.protocol.util.DeferredByteBufHolder.content(DeferredByteBufHolder.java:28) ~[velocity.jar:1.1.2]
  at com.velocitypowered.proxy.protocol.packet.PluginMessage.encode(PluginMessage.java:72) ~[velocity.jar:1.1.2]
  at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:34) ~[velocity.jar:1.1.2]
  at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:12) ~[velocity.jar:1.1.2]
  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:1.1.2]
  ... 10 more```

It should be noted that this doesn't *always* happen, but happens approximately 80% of the time. It is not player nor version specific, as when I attempt to join the proxy I typically can get in after ~3 attempts.

**Comment by astei** [comment]
I haven't been able to fully nail down this issue, and will need to debug it. To do that though, I'll need to be able to reproduce the problem on my end.

**Comment by astei** [comment]
Confirmed with some extra debugging that this is an issue in Velocity's BungeeCord plugin messaging channel support.

**Comment by astei** [comment]
Should be fixed in the latest dev build
