### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#415]
Velocity latest 1.1.x SNAPSHOT
```
java.util.concurrent.RejectedExecutionException: Task com.velocitypowered.proxy.network.netty.SeparatePoolInetNameResolver$$Lambda$874/0x000000080126eff0@341845aa rejected from java.util.concurrent.ThreadPoolExecutor@29ebc2bd[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 337]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
    at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687)
    at com.velocitypowered.proxy.network.netty.SeparatePoolInetNameResolver.doResolveAll(SeparatePoolInetNameResolver.java:85)
    at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)
    at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)
    at org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:50)
    at org.asynchttpclient.netty.request.NettyRequestSender.resolveAddresses(NettyRequestSender.java:357)
    at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:300)
    at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:142)
    at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:113)
    at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
    at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:238)
    at org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:39)
    at com.velocitypowered.proxy.connection.client.LoginSessionHandler.handle(LoginSessionHandler.java:109)
    at com.velocitypowered.proxy.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:57)
    at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:121)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:70)
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:41)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:832)
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task com.velocitypowered.proxy.network.netty.SeparatePoolInetNameResolver$$Lambda$874/0x000000080126eff0@341845aa rejected from java.util.concurrent.ThreadPoolExecutor@29ebc2bd[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 337]
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
    at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
    at com.velocitypowered.proxy.connection.client.LoginSessionHandler.lambda$handle$0(LoginSessionHandler.java:125)
    at org.asynchttpclient.netty.NettyResponseFuture.lambda$addListener$0(NettyResponseFuture.java:294)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:832)
```

**Comment by astei** [comment]
You have given us zero context here, what were you doing?

it looks like someone tried to log into the proxy while the proxy was shutting down. Not a lot we can do about that.

**Comment by ghost** [comment]
I dont know, i'm find this in my Sentry report

**Comment by astei** [comment]
Not a lot we can do here, the proxy should probably do a better job of rejecting connections but that's it. Closing since there is no bug here.
