### ISSUE TITLE
[2.0.0] Unable to register plugin listener

### ISSUE THREAD

**Issue by NEZNAMY** [PaperMC/Velocity#470]
Installing a plugin on 2.0.0 b51 will result in error when trying to load plugin(s):
```
[22:08:32] [main/ERROR]: Unable to register plugin listener for Test
java.lang.IllegalArgumentException: The plugin main instance is automatically registered.
	at com.velocitypowered.proxy.event.VelocityEventManager.register(VelocityEventManager.java:320) ~[Velocity%202.0.0%20%2351.jar:2.0.0-SNAPSHOT (git-d26d61f0-b51)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:333) ~[Velocity%202.0.0%20%2351.jar:2.0.0-SNAPSHOT (git-d26d61f0-b51)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:221) ~[Velocity%202.0.0%20%2351.jar:2.0.0-SNAPSHOT (git-d26d61f0-b51)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:81) ~[Velocity%202.0.0%20%2351.jar:2.0.0-SNAPSHOT (git-d26d61f0-b51)]
```
The plugin in question is literally nothing more than a compiled version of
```
@Plugin(id = "test", name = "Test", version = "1.0.0", description = "Test plugin", authors = {"me"})
public class Main {

	public ProxyServer server;

	@Inject
	public Main(ProxyServer server) {
		this.server = server;
	}
}
```
You can also see in the track trace that the exception does not come from plugin trying to register listener itself with a register method.

**Comment by astei** [comment]
Should be fixed by #471, thanks for reporting! It's a bit early to be playing with 2.0.0 but I'm glad someone is doing it.
