### ISSUE TITLE
bStats' random intervals are too random

### ISSUE THREAD

**Issue by NEZNAMY** [PaperMC/Velocity#476]
Unlike on bukkit where bStats data are sent 5 minutes after start and then every 30 minutes, velocity's default metrics class which I'm assuming the velocity itself is using as it is, contains very random intervals, sometimes causing delay to be too low and throw Too many requests (429).
Just let my server run after last test and this appeared in my console:
```
[13:45:04] [main/WARN]: Velocity 2.0.0 is under active development and WILL NOT WORK WITH YOUR EXISTING PLUGINS!
[13:45:05] [main/INFO]: Booting up Velocity 2.0.0-SNAPSHOT (git-efa9f6f3-b54)...
[13:45:05] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
[13:45:05] [main/WARN]: Player info forwarding is disabled! All players will appear to be connecting from the proxy and will have offline-mode UUIDs.
[13:45:05] [main/INFO]: Loading plugins...
[13:45:05] [main/INFO]: Loaded plugin test 1.0.0 by me
[13:45:05] [main/INFO]: Loaded 1 plugins
[13:45:05] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:25577
[13:45:05] [main/INFO]: Done (1.5s)!
[13:45:06] [main/INFO]: velocity.command.command-does-not-exist
[13:49:02] [bStats-Metrics/INFO]: Sent bStats metrics data: {"osName":"Windows 8.1","osArch":"amd64","osVersion":"6.3","coreCount":4,"service":{"id":4752,"customCharts":[{"chartId":"online_mode","data":{"value":"online"}},{"chartId":"velocity_version","data":{"value":"2.0.0-SNAPSHOT (git-efa9f6f3-b54)"}},{"chartId":"java_version","data":{"values":{"Java 16":{"16":1}}}},{"chartId":"managed_servers","data":{"value":3}}]},"serverUUID":"211d4779-e0a8-421c-b8fd-9762272a2ed9","metricsVersion":"2.2.0"}
[13:49:22] [bStats-Metrics/INFO]: Sent data to bStats and received response: 
[13:50:48] [bStats-Metrics/INFO]: Sent bStats metrics data: {"osName":"Windows 8.1","osArch":"amd64","osVersion":"6.3","coreCount":4,"service":{"id":4752,"customCharts":[{"chartId":"online_mode","data":{"value":"online"}},{"chartId":"velocity_version","data":{"value":"2.0.0-SNAPSHOT (git-efa9f6f3-b54)"}},{"chartId":"java_version","data":{"values":{"Java 16":{"16":1}}}},{"chartId":"managed_servers","data":{"value":3}}]},"serverUUID":"211d4779-e0a8-421c-b8fd-9762272a2ed9","metricsVersion":"2.2.0"}
[13:50:48] [bStats-Metrics/WARN]: Could not submit bStats metrics data
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/api/v2/data/server-implementation
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at com.velocitypowered.proxy.bstats.MetricsBase.sendData(MetricsBase.java:196) ~[Velocity%202.0.0%20%2354.jar:2.0.0-SNAPSHOT (git-efa9f6f3-b54)]
	at com.velocitypowered.proxy.bstats.MetricsBase.lambda$submitData$4(MetricsBase.java:161) ~[Velocity%202.0.0%20%2354.jar:2.0.0-SNAPSHOT (git-efa9f6f3-b54)]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
When I checked velocity interval code some time ago, it appeared to generate a random number and use that as refresh, sometimes being too low.
This affects both 1.1.x and 2.0.0.

**Comment by astei** [comment]
[The random delay is determined by the bStats base class](https://github.com/Bastian/bStats-Metrics/blob/master/base/src/main/java/org/bstats/MetricsBase.java#L128) and can't be controlled by Velocity itself.

If there is an issue, it is in bStats, not Velocity. I'm closing this as out of scope.

**Comment by astei** [comment]
I have filed Bastian/bStats-Metrics#84 as an attempt to fix the issue. It ensures that the delay of the second request to bStats will always be greater than the first delay.
