### ISSUE TITLE
 java.lang.NoClassDefFoundError (via version)

### ISSUE THREAD

**Issue by jokbon** [PaperMC/Velocity#529]
[00:35:22 ERROR]: Exception in thread "main" java.lang.NoClassDefFoundError: net/kyori/text/Component
[00:35:22 ERROR]:       at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
[00:35:22 ERROR]:       at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3305)
[00:35:22 ERROR]:       at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2495)
[00:35:22 ERROR]:       at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:292)
[00:35:22 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:117)
[00:35:22 ERROR]:       at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:716)
[00:35:22 ERROR]:       at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:54)
[00:35:22 ERROR]:       at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:36)
[00:35:22 ERROR]:       at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:52)
[00:35:22 ERROR]:       at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:35)
[00:35:22 ERROR]:       at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:27)
[00:35:22 ERROR]:       at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:99)
[00:35:22 ERROR]:       at com.google.inject.internal.AbstractProcessor.lambda$process$0(AbstractProcessor.java:53)
[00:35:22 ERROR]:       at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[00:35:22 ERROR]:       at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[00:35:22 ERROR]:       at com.google.inject.internal.AbstractProcessor.process(AbstractProcessor.java:50)
[00:35:22 ERROR]:       at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:216)
[00:35:22 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
[00:35:22 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:87)
[00:35:22 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:69)
[00:35:22 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:59)
[00:35:22 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119)
[00:35:22 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:152)
[00:35:22 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:272)
[00:35:22 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:214)
[00:35:22 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:75)
[00:35:22 ERROR]: Caused by: java.lang.ClassNotFoundException: net.kyori.text.Component
[00:35:22 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83)
[00:35:22 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60)
[00:35:22 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[00:35:22 ERROR]:       ... 26 more

**Comment by jokbon** [comment]
this isusue strangely reapeared out of nowhere, after viaversion fixed compatibility it ran fine until next restart so iam not sure what caused it and on what end. What confused me that it ran fine until it got restarted for 2nd time.

**Comment by jokbon** [comment]
it even let 1.8 player to conect, but it was laggy and world was loading super slowly on theyr side. later after trying restarting (only updated skinrestorer) it again throwing class not found error

**Comment by astei** [comment]
You have a plugin that’s not compatible with Velocity 3.0.0
