### ISSUE TITLE
Exception during runtime.

### ISSUE THREAD

**Issue by DeprecatedLuke** [PaperMC/Velocity#541]
```
[20:57:13 ERROR]: Exception during connect; status = null
java.util.concurrent.CompletionException: java.io.IOException: Unexpectedly disconnected from remote server
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
        at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:206) ~[velocity.jar:1.1.9]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:112) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.1.9]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:1.1.9]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.1.9]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velocity.jar:1.1.9]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.1.9]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.9]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity.jar:1.1.9]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) ~[velocity.jar:1.1.9]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity.jar:1.1.9]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:1.1.9]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity.jar:1.1.9]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:1.1.9]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:1.1.9]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:1.1.9]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:205) ~[velocity.jar:1.1.9]
        ... 26 more
> [20:57:13 ERROR]: java.util.concurrent.CompletionException: java.io.IOException: Unexpectedly disconnected from remote server
> [20:57:13 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
> [20:57:13 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
> [20:57:13 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
> [20:57:13 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> [20:57:13 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
> [20:57:13 ERROR]:       at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:206)
> [20:57:13 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:112)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
> [20:57:13 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
> [20:57:13 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
> [20:57:13 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
> [20:57:13 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
> [20:57:13 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
> [20:57:13 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
> [20:57:13 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
> [20:57:13 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> [20:57:13 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> [20:57:13 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
> [20:57:13 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> [20:57:13 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> [20:57:13 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> [20:57:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:834)
> [20:57:13 ERROR]: Caused by: java.io.IOException: Unexpectedly disconnected from remote server
> [20:57:13 ERROR]:       at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:205)
> [20:57:13 ERROR]:       ... 26 more
```

Not sure if an unhandled exception or expected behavior.

**Comment by astei** [comment]
You have given us nothing to work with here. Generally, this indicates a server-side issue and is not an issue with Velocity.

**Comment by DeprecatedLuke** [comment]
Oh, I thought this was a NullPointerException from the first exception. Nevermind.
