### ISSUE TITLE
Error with packets on a modded fabric server under Velocity.

### ISSUE THREAD

**Issue by SansSerif1** [PaperMC/Velocity#573]
Hi!

Recently, I started a All Of Fabric 3 Modpack server and put in under velocity, using FabricProxy-Lite mod. When I join, it spits out this.

`exception encount
ered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@1
cfa7f4d
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocit
ypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 
1.16.4 State PLAY ID 10
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecod
eFailure(MinecraftDecoder.java:128) ~[velocity-301.jar:3.0.1]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(M
inecraftDecoder.java:83) ~[velocity-301.jar:3.0.1]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead
(MinecraftDecoder.java:58) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[velocity-301.jar:3.0.1]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[velocity-301.jar:3.0.1]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandle
r.java:286) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[velocity-301.jar:3.0.1]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:324) ~[velocity-301.jar:3.0.1]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:311) ~[velocity-301.jar:3.0.1]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:432) ~[velocity-301.jar:3.0.1]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:276) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Defau
ltChannelPipeline.java:1410) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:919) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:166) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:719) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:655) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:581) ~[velocity-301.jar:3.0.1]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[veloci
ty-301.jar:3.0.1]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThread
EventExecutor.java:986) ~[velocity-301.jar:3.0.1]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74) ~[velocity-301.jar:3.0.1]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
unnable.java:30) ~[velocity-301.jar:3.0.1]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

Does anyone know how to fix this?
Thanks in advance.

**Comment by astei** [comment]
Install the CrossStitch mod like the documentation tells you to

**Comment by SansSerif1** [comment]
Hello! Thanks for replying, but, when I install crossstitch, it throws the same error. There is also a text at the end:
`Caused by: java.lang.IllegalArgumentException: Argument type identifier minecraft:ftbteams_team unknown.
	at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:75) ~[velocity-301.jar:3.0.1]
	at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:208) ~[velocity-301.jar:3.0.1]
	at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:86) ~[velocity-301.jar:3.0.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-301.jar:3.0.1]
	... 32 more
`

Does that mean that FTB Teams mod is broken, or is it something else?

**Comment by astei** [comment]
Yes.
