### ISSUE TITLE
Velocity proxy-error while connecting to a forge server

### ISSUE THREAD

**Issue by KiwiJuice08** [PaperMC/Velocity#592]
I get the following error, if I trie to connect to my forge server via velocity.

unable to connect to server sky

java.io.IOException: Unexpectedly disconnected from remote server

at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.disconnected(LoginSessionHandler.java:123) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:91) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.handler.flow.FlowControlHandler.channelInactive(FlowControlHandler.java:125) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:1.0.11-SNAPSHOT (git-b14e7e65-b176)]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by astei** [comment]
You’re running an unsupported version of Velocity

**Comment by KiwiJuice08** [comment]
now I changed the velocity version but I get this error now:

com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.

This is usually because the remote server does not have BungeeCord IP forwarding correctly enabled.

See https://docs.velocitypowered.com/en/latest/users/player-info-forwarding.html for instructions on how to configure player info forwarding correctly.

**Comment by astei** [comment]
Well, you messed up forwarding. Please read the wiki.
