### ISSUE TITLE
"Unable to connect to creative, please try again later."

### ISSUE THREAD

**Issue by Pairman** [PaperMC/Velocity#621]
Hello, can anyone help me with this issue? I'm sure that my velocity is configured properly (on my other servers the same velocity configuration works fine).

I only installed multilogin plugin.

But every time I connect to this server it shows "Unable to connect to creative, please try again later."

 Can anyone help me with it? Thanks in advance!

The full log:
[13:33:08] [main/INFO]: Booting up Velocity 3.1.1...
[13:33:08] [main/INFO]: Loading localizations...
[13:33:08] [main/INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[13:33:08] [main/INFO]: Loading plugins...
[13:33:08] [main/INFO]: Loading libraries...
[13:33:11] [main/INFO]: Loaded plugin multilogin 0.3.10 by ksqeib, CaaMoe
[13:33:11] [main/INFO]: Loaded 1 plugins
[13:33:11] [Velocity Async Event Executor - #0/INFO]: 加载文件: config.yml
[13:33:12] [Velocity Async Event Executor - #0/INFO]: 添加 Yggdrasil 账户验证服务器 Demo Yggdrasil(demo), 但未启用它。
[13:33:12] [Velocity Async Event Executor - #0/INFO]: 添加 Yggdrasil 账户验证服务器 OFFICIAL(official)。
[13:33:12] [Velocity Async Event Executor - #0/INFO]: 添加 Yggdrasil 账户验证服务器 LITTLESKIN(littleSkin)。
[13:33:12] [Velocity Async Event Executor - #0/INFO]: 成功连接到 H2 数据库
[13:33:12] [Velocity Async Event Executor - #0/INFO]: 插件加载完毕
[13:33:12] [Netty epoll Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:13078
[13:33:12] [main/INFO]: Done (5.08s)!
[13:33:44] [MultiLogin Async #1/INFO]: Authentication passed, login allowed. (user: Pairman, in game uuid: 77ced09e-b781-41b4-a76c-e44f87b6b1c6, online uuid: 77ced09e-b781-41b4-a76c-e44f87b6b1c6, yggdrasil: official)
[13:33:44] [Netty epoll Worker #3/INFO]: [connected player] Pairman (/127.0.0.1:55774) has connected
[13:33:44] [Netty epoll Worker #3/INFO]: [server connection] Pairman -> creative has connected
[13:33:44] [Netty epoll Worker #3/ERROR]: [server connection] Pairman -> creative: exception encountered in com.velocitypowered.proxy.connection.backend.TransitionSessionHandler@35ca80ed
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.BossBar Direction CLIENTBOUND Protocol 1.18 State PLAY ID d
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.1-98.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(4): PooledSlicedByteBuf(ridx: 2, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 142, widx: 158, cap: 8192))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readUuid(ProtocolUtils.java:261) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.packet.BossBar.decode(BossBar.java:118) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.1-98.jar:3.1.1]
	... 30 more
[13:33:44] [Netty epoll Worker #3/INFO]: [server connection] Pairman -> creative has disconnected
[13:33:44] [Netty epoll Worker #3/ERROR]: [connected player] Pairman (/127.0.0.1:55774): unable to connect to server creative
java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:207) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:115) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.1-98.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:33:44] [Netty epoll Worker #3/INFO]: [connected player] Pairman (/127.0.0.1:55774) has disconnected: Unable to connect you to creative. Please try again later.
[13:35:00] [MultiLogin Async #4/INFO]: Authentication passed, login allowed. (user: Pairman, in game uuid: 77ced09e-b781-41b4-a76c-e44f87b6b1c6, online uuid: 77ced09e-b781-41b4-a76c-e44f87b6b1c6, yggdrasil: official)
[13:35:00] [Netty epoll Worker #0/INFO]: [connected player] Pairman (/127.0.0.1:55864) has connected
[13:35:00] [Netty epoll Worker #0/INFO]: [server connection] Pairman -> creative has connected
[13:35:00] [Netty epoll Worker #0/ERROR]: [server connection] Pairman -> creative: exception encountered in com.velocitypowered.proxy.connection.backend.TransitionSessionHandler@15b00d0e
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.BossBar Direction CLIENTBOUND Protocol 1.18 State PLAY ID d
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.1-98.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(4): PooledSlicedByteBuf(ridx: 2, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 4096))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readUuid(ProtocolUtils.java:261) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.packet.BossBar.decode(BossBar.java:118) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.1-98.jar:3.1.1]
	... 28 more
[13:35:00] [Netty epoll Worker #0/INFO]: [server connection] Pairman -> creative has disconnected
[13:35:00] [Netty epoll Worker #0/ERROR]: [connected player] Pairman (/127.0.0.1:55864): unable to connect to server creative
java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:207) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:115) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.1-98.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.1-98.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:35:00] [Netty epoll Worker #0/INFO]: [connected player] Pairman (/127.0.0.1:55864) has disconnected: Unable to connect you to creative. Please try again later.
[13:38:51] [Thread-3/INFO]: Shutting down the proxy...
[13:38:51] [Thread-3/INFO]: Closing endpoint /0.0.0.0:13078

**Comment by Pairman** [comment]
And in my minecraft server it shows "Pairman joined the game ... Pairman lost connection: Disconnected ... Pairman left the game"

**Comment by Xernium** [comment]
The server is sending an invalid BossBar
While that may not directly crash or error on the client it will do that on velocity because velocity has to re-encode that packet; and it can’t do that if it is invalid.
Please check that and get back here;
The full issue: The player receives a bossbar for an invalid entity UUID

**Comment by astei** [comment]
Closing due to inactivity.
