### ISSUE TITLE
Error with packets on a modded fabric server under Velocity

### ISSUE THREAD

**Issue by half-nothing** [PaperMC/Velocity#684]
Hi.
I started a All Of Fabric 3 Modpack server and put in under velocity, using FabricProxy-Lite mod. When I join, something went wrong.I copyed some error log under.

Here is the All Of Fabric 3 Modpack Server's error log:
`[09:02:19] [Server thread/INFO] (MinecraftServer) skyfsj joined the game
[09:02:19] [Server thread/INFO] (class_3244) skyfsj lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2982704 into 3
[09:02:19] [Server thread/INFO] (MinecraftServer) skyfsj left the game`

And here is the Velocity Server's error log:
`[08:55:59 ERROR]: [server connection] skyfsj -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@5d9b77c1
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

I have seen the #573 and installed the CrossStitch mod,but unfortunately it did not work.
So what should I do now?

**Comment by n1klasse** [comment]
Do you have the modern ip forwarding enabled?

**Comment by Xernium** [comment]
Cannot reproduce, also can't debug due to the nature of fabric. This looks to me like the modpack is breaking a vanilla feature the proxy needs to interact with. I recommend you remove mods one by one until it doesnt happen anymore. When you find the cause of the problem please contact the mod author.
