### ISSUE TITLE
[Guice/ErrorInjectingConstructor]: IllegalArgumentException: VelocityAccountSystem does not have a container.

### ISSUE THREAD

**Issue by Azodox** [PaperMC/Velocity#766]
Hey,

I recently made some changes to my velocity plugin and upgraded my velocity server to the latest version but when I started my server this error occurs concerning my plugin :

```
[14:33:11 ERROR]: Can't create plugin accountsystem-velocity
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: VelocityAccountSystem does not have a container.
  at VelocityAccountSystem.<init>(VelocityAccountSystem.java:38)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating VelocityAccountSystem

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityAccountSystem:    "net.valneas.account.VelocityAccountSystem"
VelocityPluginModule:     "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:221) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
Caused by: java.lang.IllegalArgumentException: net.valneas.account.VelocityAccountSystem does not have a container.
        at com.velocitypowered.api.plugin.PluginManager.lambda$ensurePluginContainer$0(PluginManager.java:69) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.velocitypowered.api.plugin.PluginManager.ensurePluginContainer(PluginManager.java:69) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.velocitypowered.proxy.event.VelocityEventManager.register(VelocityEventManager.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at net.valneas.account.VelocityAccountSystem.<init>(VelocityAccountSystem.java:59) ~[?:?]
        at net.valneas.account.VelocityAccountSystem$$FastClassByGuice$$772430.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.valneas.account.VelocityAccountSystem$$FastClassByGuice$$772430.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a1391a5-b155)]
        ... 6 more
```

I admit I'm not very familiar with Google's Guice but I followed the documentation and my main class seems not to have differences that might causes this error, here is my main class :

```java
package net.valneas.account;

import com.google.inject.Inject;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.plugin.annotation.DataDirectory;
import com.velocitypowered.api.proxy.ProxyServer;
import dev.morphia.Datastore;
import lombok.Getter;
import net.valneas.account.listener.PermissionSetupListener;
import net.valneas.account.mongo.Mongo;
import net.valneas.account.permission.VelocityPermissionDatabase;
import net.valneas.account.rank.VelocityRankHandler;
import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.tomlj.Toml;
import org.tomlj.TomlParseResult;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;
import java.nio.file.Paths;

@Plugin(id = "@id@", name = "@name@", version = "@version@")
public class VelocityAccountSystem {

    private final ProxyServer server;
    private final Logger logger;
    private final Path dataDirectory;
    private final Mongo mongo;
    private final @Getter Datastore datastore;
    private final @Getter VelocityPermissionDatabase permissionDatabase;
    private final @Getter VelocityRankHandler rankHandler;
    private TomlParseResult config;

    @Inject
    public VelocityAccountSystem(ProxyServer server, Logger logger, @DataDirectory Path dataDirectory) throws IOException {
        this.server = server;
        this.logger = logger;

        if(!dataDirectory.toFile().exists()) {
            dataDirectory.toFile().mkdirs();
        }

        this.dataDirectory = dataDirectory;
        this.initConfig();

        this.mongo = new Mongo(
                getConfig().getString("MongoDB.username"),
                getConfig().getString("MongoDB.authDatabase"),
                getConfig().getString("MongoDB.password"),
                getConfig().getString("MongoDB.host"),
                getConfig().getLong("MongoDB.port").intValue());
        this.datastore = new MorphiaInitializer(this.getClass(), this.mongo.getMongoClient(), getConfig().getString("MongoDB.database"), new String[]{"net.valneas.account"}).getDatastore();
        this.rankHandler = new VelocityRankHandler(this.getDatastore());
        this.permissionDatabase = new VelocityPermissionDatabase(this);

        server.getEventManager().register(this, new PermissionSetupListener(this));
        logger.info("Account System plugin for Velocity successfully loaded. v@version@");
    }

    private void initConfig() throws IOException {
        var baseConfig = new File("config.toml");
        var config = new File(dataDirectory.toFile(), "config.toml");

        if(!config.exists()) {
            config.createNewFile();
        }

        if(!FileUtils.contentEquals(config, baseConfig) && config.length() != 0){
            logger.info("File '" + config.getPath() + "' content doesn't equals to '" + baseConfig.getPath() + "' and is not empty, skipping files copy.");
        }else {
            InputStream in = getClass().getResourceAsStream("/" + config.getName());
            FileOutputStream out = new FileOutputStream(config);

            byte[] buf = new byte[1024];
            int n;

            while ((n = in.read(buf)) >= 0) {
                out.write(buf, 0, n);
            }

            in.close();
            out.close();
            logger.info("File '" + config.getPath() + "' copied from resources.");
        }

        this.config = Toml.parse(Paths.get(this.getDataDirectory() + File.separator + config.getName()));
        this.config.errors().forEach(error -> System.err.println(error.toString()));
    }

    public Path getDataDirectory() {
        return dataDirectory;
    }

    public TomlParseResult getConfig() {
        return config;
    }

    public Mongo getMongo() {
        return mongo;
    }
}
```
Any idea on why and how fix it? Thanks in advance.

**Comment by 4drian3d** [comment]
In the constructor of the main class of your plugin you only have to assign the injected variables to their respective values. To initialize the plugin, you must do it in the event https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/proxy/ProxyInitializeEvent.html as it says it in the wiki https://docs.papermc.io/velocity/dev/api-basics#a-word-of-caution

**Comment by Azodox** [comment]
Oh my bad, thank you.
