### ISSUE TITLE
error Incorrect Argument for command at position 9:Velocity

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#773]
when I write all the velocity commands to the console it says:
[23:17:54 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[23:17:54 INFO]: Velocity configuration successfully reloaded.
[23:17:54 ERROR]: Can't bind to /0.0.0.0:25565
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194) ~[?:?]
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164) ~[?:?]
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
        at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:201) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:196) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.1.2-SNAPSHOT (git-662fbc4e-b159)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

and besides the velocity version command
My Config: https://drive.google.com/file/d/1DpjbuhzTejS517QX2ahQqtGvK-PDYKn4/view?usp=sharing

**Comment by Xernium** [comment]
> Address already in use     

You already have something running on port 25565
You either have an orphaned instance running or you have a server on that port.
