### ISSUE TITLE
1.19 Minecraft clients cannot join the proxy

### ISSUE THREAD

**Issue by vlssu** [PaperMC/Velocity#775]
This is what shows up on the proxy's log when a 1.19 client tries to join:
```
[17:39:56 INFO]: [connected player] ValiantShishu (/ip:3108) has connected
[17:39:56 INFO]: [server connection] ValiantShishu -> optifine_survival has connected
[17:39:56 INFO]: [connected player] ValiantShishu (/ip:3108) has disconnected: Your connection to optifine_survival encountered a problem.
[17:39:56 INFO]: [server connection] ValiantShishu -> optifine_survival has disconnected
```
![image](https://user-images.githubusercontent.com/43847794/175808440-9b7b4ea1-9cdf-4834-9dec-43aa90d06f17.png)

Minecraft server logs:
```
[17:43:12 INFO]: UUID of player ValiantShishu is uuid
[17:43:12 INFO]: ValiantShishu joined the game
[17:43:12 INFO]: ValiantShishu[/ip:34188] logged in with entity id 443498 at ([world]-282.56085, 73.5625, 4045.6094)
[17:43:12 INFO]: ValiantShishu lost connection: Disconnected
[17:43:12 INFO]: ValiantShishu left the game
```
## some content additions
The agent's `online_mode` is set to `true` or `false` is the same prompt
Use genuine access or use the external login Yggdrasil API of [blessing-skin-server](https://github.com/bs-community/blessing-skin-server), the prompts are the same.
But I got in normally when using 1.18.
And the velocity when the last version supported 1.18 works fine.

## configuration file
```
# Config version. Do not change this
config-version = "2.0"
# What port should the proxy be bound to? By default, we'll bind to all addresses on port 25577.
bind = "0.0.0.0:10172"
# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Legacy color codes and JSON are accepted.
motd = "&#09add3A Velocity Server"
# What should we display for the maximum number of players? (Velocity does not support a cap
# on the number of players online.)
show-max-players = 2022
# Should we authenticate players with Mojang? By default, this is on.
online-mode = true
# Should the proxy enforce the new public key security standard? By default, this is on.
force-key-authentication = false
# If client's ISP/AS sent from this proxy is different from the one from Mojang's
# authentication server, the player is kicked. This disallows some VPN and proxy
# connections but is a weak form of protection.
prevent-client-proxy-connections = false
# Should we forward IP addresses and other data to backend servers?
# Available options:
# - "none":        No forwarding will be done. All players will appear to be connecting
#                  from the proxy and will have offline-mode UUIDs.
# - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
#                  if you run servers using Minecraft 1.12 or lower.
# - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
#                  unable to implement network level firewalling (on a shared host).
# - "modern":      Forward player IPs and UUIDs as part of the login process using
#                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "bungeeguard"
# If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
# The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"
# Announce whether or not your server supports Forge. If you run a modded server, we
# suggest turning this on.
# 
# If your network runs one modpack consistently, consider using ping-passthrough = "mods"
# instead for a nicer display in the server list.
announce-forge = true
# If enabled (default is false) and the proxy is in online mode, Velocity will kick
# any existing player who is online if a duplicate connection attempt is made.
kick-existing-players = false
# Should Velocity pass server list ping requests to a backend server?
# Available options:
# - "disabled":    No pass-through will be done. The velocity.toml and server-icon.png
#                  will determine the initial server list ping response.
# - "mods":        Passes only the mod list from your backend server into the response.
#                  The first server in your try list (or forced host) with a mod list will be
#                  used. If no backend servers can be contacted, Velocity won't display any
#                  mod information.
# - "description": Uses the description and mod list from the backend server. The first
#                  server in the try (or forced host) list that responds is used for the
#                  description and mod list.
# - "all":         Uses the backend server's response as the proxy response. The Velocity
#                  configuration is used if no servers could be contacted.
ping-passthrough = "DISABLED"
# If not enabled (default is true) player IP addresses will be replaced by <ip address withheld> in logs
enable-player-address-logging = true
forwarding-secret = "1M1xzaiAoF38"

[servers]
	# Configure your servers here. Each key represents the server's name, and the value
	# represents the IP address of the server to connect to.
	login = "127.0.0.1:25561"
	optifine_survival = "127.0.0.1:25562"
	# In what order we should try servers when a player logs in or is kicked from a server.
	try = ["optifine_survival"]
	# try = ["login", "optifine_survival"]

[forced-hosts]
	# Configure your forced hosts here.
	"login.vlssu.cn" = ["login"]
	"optifine_survival.vlssu.cn" = ["optifine_survival"]

[advanced]
	# How large a Minecraft packet has to be before we compress it. Setting this to zero will
	# compress all packets, and setting it to -1 will disable compression entirely.
	compression-threshold = 256
	# How much compression should be done (from 0-9). The default is -1, which uses the
	# default level of 6.
	compression-level = -1
	# How fast (in milliseconds) are clients allowed to connect after the last connection? By
	# default, this is three seconds. Disable this by setting this to 0.
	login-ratelimit = 3000
	# Specify a custom timeout for connection timeouts here. The default is five seconds.
	connection-timeout = 5000
	# Specify a read timeout for connections here. The default is 30 seconds.
	read-timeout = 30000
	# Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
	# don't enable it.
	haproxy-protocol = false
	# Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
	tcp-fast-open = true
	# Enables BungeeCord plugin messaging channel support on Velocity.
	bungee-plugin-message-channel = true
	# Shows ping requests to the proxy from clients.
	show-ping-requests = false
	# By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
	# loses connection to the server without an explicit disconnect message by attempting to fall the
	# user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
	# can disable this setting to use the BungeeCord behavior.
	failover-on-unexpected-server-disconnect = true
	# Declares the proxy commands to 1.13+ clients.
	announce-proxy-commands = true
	# Enables the logging of commands
	log-command-executions = false
	# Enables logging of player connections when connecting to the proxy, switching servers
	# and disconnecting from the proxy.
	log-player-connections = true

[query]
	# Whether to enable responding to GameSpy 4 query responses or not.
	enabled = false
	# If query is enabled, on what port should the query protocol listen on?
	port = 10172
	# This is the map name that is reported to the query services.
	map = "VLssu"
	# Whether plugins should be shown in query response by default or not
	show-plugins = false
```

**Comment by EterNityCH** [comment]
你是怎么提供自订session/skin服务器？ 唯一支援的方式是使用以下jvm flag:

`-Dmojang.sessionserver=“https://sessionserver.mojang.com/session/minecraft/hasJoined“ `

请问你有将 `force-key-authentication` 启用吗？

请注意 你无法使用自定义的密钥认证、

Velocity使用自备的Yggdrasil key、你必须更改如果你要使用的自制的讯息密钥认证。

**Comment by vlssu** [comment]
> 你是怎么提供自订session/skin服务器？ 唯一支援的方式是使用以下jvm flag:
> 
> `-Dmojang.sessionserver=“https://sessionserver.mojang.com/session/minecraft/hasJoined“ `
> 
> 请问你有将 `force-key-authentication` 启用吗？
> 
> 请注意 你无法使用自定义的密钥认证、
> 
> Velocity使用自备的Yggdrasil key、你必须更改如果你要使用的自制的讯息密钥认证。

使用java正版进入服务器我也尝试了
两个密钥认证在 `force-key-authentication`启用过禁用的状态都已尝试
服务器的提示依旧是一样的。
使用外置登录的情况下使用以下参数
```
-javaagent:{path/to/authlib-injector.jar}=https://skin.vlssu.com/api/yggdrasil
```
jvm 参数中的`authlib-injector.jar`下载链接 https://authlib-injector.yushi.moe/~download/

在java正版和外置登录我都已尝试，提示都是一样的！！

I also tried to use the genuine java to enter the server
Both key authentications have been attempted with `force-key-authentication` enabled and disabled
The server prompt is still the same.
I am using the following parameters in the case of Yggdrasil
```
-javaagent:authlib-injector.jar=https://skin.vlssu.com/api/yggdrasil
```
`authlib-injector.jar` download link in jvm parameters https://authlib-injector.yushi.moe/~download/

I have tried both in java genuine and Yggdrasil, the tips are the same!

**Comment by vlssu** [comment]
但是，按照日志看，Velocity应该是放过了，但是在转发到子服务器时出现了一些问题。但是1.18是可以正常进入的，就很奇怪，只有1.19是没办法正常进入的。

However, according to the log, Velocity should have passed the verification, but there are some problems when forwarding to the sub-server? But 1.18 can be entered normally, it is very strange, only 1.19 can not enter normally.

**Comment by EterNityCH** [comment]
你能尝试这个吗？ 有任何新的错误、请在这里回报、请提供完整的log资讯。

https://github.com/Xernium/Velocity/commit/ca86e58c2d697881a2d508b2ce70f9f531a67799#commitcomment-77027985

**Comment by vlssu** [comment]
> 你能尝试这个吗？ 有任何新的错误、请在这里回报、请提供完整的log资讯。
> 
> [Xernium@ca86e58#commitcomment-77027985](https://github.com/Xernium/Velocity/commit/ca86e58c2d697881a2d508b2ce70f9f531a67799#commitcomment-77027985)

```
[12:15:22 INFO]: Done (2.43s)!
[authlib-injector] [INFO] Httpd is running on port 36683
[authlib-injector] [INFO] Transformed [com.velocitypowered.proxy.connection.client.InitialLoginSessionHandler] with [Constant URL Transformer]
[12:15:24 INFO]: [connected player] ValiantShishu (/ip:25329) has connected
[12:15:24 INFO]: [server connection] ValiantShishu -> optifine_survival has connected
[12:15:24 INFO]: [connected player] ValiantShishu (/ip:25329) has disconnected: 您的连接发生内部错误。
[12:15:24 INFO]: [server connection] ValiantShishu -> optifine_survival has disconnected
[12:15:41 INFO]: This command does not exist.
[12:15:45 INFO]: [connected player] ValiantShishu (/ip:25351) has connected
[12:15:45 INFO]: [server connection] ValiantShishu -> optifine_survival has connected
[12:15:45 ERROR]: com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
[12:15:45 INFO]: [connected player] ValiantShishu (/ip:25351) has disconnected: 您与 optifine_survival 的连接出现问题。
[12:15:45 INFO]: [server connection] ValiantShishu -> optifine_survival has disconnected
```
打开了 `-Dvelocity.packet-decode-logging=true`进入后的报错  @EterNityCH 
```
[18:13:31 INFO]: [connected player] ValiantShishu (/ip:3339) has connected
[18:13:31 INFO]: [server connection] ValiantShishu -> optifine_survival has connected
[18:13:31 ERROR]: io.netty.handler.codec.CorruptedFrameException: Packet sent for class dev.simplix.protocolize.velocity.packets.GeneratedHeldItemChangeWrapper was too big (expected 3 bytes, got 8 bytes)
[18:13:31 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleOverflow(MinecraftDecoder.java:109)
[18:13:31 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:87)
[18:13:31 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:13:31 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:13:31 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:13:31 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[18:13:31 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[18:13:31 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[18:13:31 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:13:31 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:13:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:13:31 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:13:31 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[18:13:31 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[18:13:31 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[18:13:31 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[18:13:31 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:13:31 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[18:13:31 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[18:13:31 INFO]: [connected player] ValiantShishu (/ip:3339) has disconnected: 您与 optifine_survival 的连接出现问题。
[18:13:31 INFO]: [server connection] ValiantShishu -> optifine_survival has disconnected
```

**Comment by astei** [comment]
closing this as this is an issue with Protocolize, not Velocity
