### ISSUE TITLE
Connect to Moded Server may failed when connection is slow

### ISSUE THREAD

**Issue by Longtianmu** [PaperMC/Velocity#796]
I am using latest build Velocity on papermc.io
The connection betwenn Velocity and backend server is Zerotier(UDP)
I can join Moded server successfull one times in ten tries.
On the backend, it will show a Timed out log.
On velocity, the log is
>Exception during connect; status = null
java.util.concurrent.CompletionException: java.io.IOException: Unexpectedly disconnected from remote server
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at java.lang.Thread.run(Thread.java:833) [?:?]
>Caused by: java.io.IOException: Unexpectedly disconnected from remote server
at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:208) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]

The ping between them is 25ms.

**Comment by Longtianmu** [comment]
The timeout of velocity and fml have been set to 120seconds
There are 9 mods of Forge Server

**Comment by electronicboy** [comment]
generally hard to say, stuff like this is generally down to mods stalling the connection process due to trying to do something which generally isn't supported within proxied environments

**Comment by Longtianmu** [comment]
Even there are no mods on forge server
The error still exists.
The log on the forge just stucks here and then timed out
```
[20:36:00] [Server thread/TRACE] [FML]: Handshake channel activating
[20:36:00] [Server thread/DEBUG] [FML]: FMLHandshakeServerState: null->FMLHandshakeServerState$1:START
[20:36:00] [Server thread/DEBUG] [FML]:   Next: HELLO
```
