### ISSUE TITLE
exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@316174c9

### ISSUE THREAD

**Issue by E4zily** [PaperMC/Velocity#813]
Hello,

I sometimes can not join my server and this is what shows up in the logs.

`[12:42:38 INFO]: [connected player] [private] (/[private]:28656) has disconnected: An internal error occurred in your connection.
[12:42:38 ERROR]: [connected player] [private] (/[private]:28656): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@316174c9
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Invalid token
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:230) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleGeneric(BackendPlaySessionHandler.java:293) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid token
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:306) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:237) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:48) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[server.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        ... 61 more`

what should i do to fix this?

thank you

**Comment by AVuTuVA** [comment]
What plugins are there??

**Comment by E4zily** [comment]
LimboAPI, LimboFilter, LuckPerms, Skungee, ViaVersion, ViaRewind, ViaBackwards.

**Comment by KoxSosen** [comment]
I believe this is a Via issue, can you try removing all Via plugins, and see if the issue still persists?

**Comment by E4zily** [comment]
I switched the Via plugins to the other servers. Seems to be good now.

**Comment by AVuTuVA** [comment]
Do not place Via* plugins on a proxy, this will only cause extra load and only errors
