### ISSUE TITLE
Player can't join server

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#818]
version velocity: #166
`Wystąpił błąd wewnętrzny w twoim połączeniu.
[21:12:00 ERROR]: [connected player] Marrysia2009 (/****): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@1de39061
java.lang.IllegalStateException: Not connected to server!
        at com.velocitypowered.proxy.connection.client.ConnectedPlayer.ensureAndGetCurrentServer(ConnectedPlayer.java:236) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:271) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at com.velocitypowered.proxy.protocol.packet.chat.PlayerCommand.handle(PlayerCommand.java:237) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.1.2-SNAPSHOT (git-8344082b-b166)]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by AVuTuVA** [comment]
Is there a bug on build 167?
