### ISSUE TITLE
Invalid Kicking

### ISSUE THREAD

**Issue by TheWylot** [PaperMC/Velocity#832]
on 400 Players people get kicked with this reasons
exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@235465c
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

my ip forwarding is legacy and is ok with all servers 
it gives me an error too 
[11:58:57] [Netty epoll Worker #0/ERROR]: Exception during connect; status = null
java.util.concurrent.CompletionException: com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
This is usually because the remote server does not have BungeeCord IP forwarding correctly enabled.
See https://velocitypowered.com/wiki/users/forwarding/ for instructions on how to configure player info forwarding correctly.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
This is usually because the remote server does not have BungeeCord IP forwarding correctly enabled.
See https://velocitypowered.com/wiki/users/forwarding/ for instructions on how to configure player info forwarding correctly.

**Comment by electronicboy** [comment]
The only information that we've got here is that the connection was closed improperly, they're currently in the velocity-help channel
