### ISSUE TITLE
Errors in console/log file when backend server in online-mode, velocity-3.1.2-SNAPSHOT-177

### ISSUE THREAD

**Issue by onovozhenov** [PaperMC/Velocity#849]
Velocity spams errors in console, while trying to connect to backend server in online-mode. Latest builds of paper and velocity.

`18:03:58] [Netty NIO Worker #1/INFO]: [server connection] bleazzz -> test has connected
[18:03:58] [Netty NIO Worker #1/ERROR]: [server connection] bleazzz -> test: exception encountered in com.velocitypowered.proxy.connection.backend.LoginSessionHandler@f8b3559
java.lang.IllegalStateException: Backend server is online-mode!
	at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.handle(LoginSessionHandler.java:75) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:87) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[18:03:58] [Netty NIO Worker #1/INFO]: [server connection] bleazzz -> test has disconnected
[18:03:58] [Netty NIO Worker #1/ERROR]: [connected player] bleazzz (/127.0.0.1:55747): unable to connect to server test
java.lang.IllegalStateException: Backend server is online-mode!
	at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.handle(LoginSessionHandler.java:75) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:87) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[18:03:58] [Netty NIO Worker #1/INFO]: [connected player] bleazzz (/127.0.0.1:55747) has disconnected: Не удалось подключить вас к серверу test. Пожалуйста, попробуйте снова через некоторое время.`

**Comment by 4drian3d** [comment]
Velocity is in responsible for authentication, so it must be in online mode, but all your connected servers must be in offline mode https://docs.papermc.io/velocity/getting-started#configuring-your-servers

**Comment by Xernium** [comment]
This behavior is intentional. Refer to the Velocity FAQ on the papermc website for setting up your network.
