### ISSUE TITLE
ProxyPingEvent to tcpshield 

### ISSUE THREAD

**Issue by authorless** [PaperMC/Velocity#850]
am faced with a problem that constantly torments my proxy server when logging on to the server. Namely, he writes a constant error when a player enters the server. Always writes this message: Couldn't pass ProxyPingEvent to tcpshield

I tried to use any ways to solve this problem, but it didn't give me anything. All to no avail. Although this error does not interfere with work, it constantly appears.

```
Couldn't pass ProxyPingEvent to tcpshield
net.tcpshield.tcpshield.util.exception.manipulate.PlayerManipulationException: An exception occured during the handshake process
at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.disconnect(VelocityPlayer.java:123) ~[?:?]
at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.handleEvent(VelocityHandshakeHandler.java:51) ~[?:?]
at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.onProxyPing(VelocityHandshakeHandler.java:45) ~[?:?]
at net.tcpshield.tcpshield.velocity.handler.Lmbda$37.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler$$Lambda$397/0x0000000089328210.executeAsync(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
at com.velocitypowered.proxy.event.VelocityEventManager$$Lambda$402/0x0000000089339470.run(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:883) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.HandshakeSessionHandler$LegacyInboundConnection.connection to com.velocitypowered.proxy.connection.client.ConnectedPlayer
at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
at java.lang.reflect.Field.get(Field.java:419) ~[?:?]
at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.getMinecraftConnection(VelocityPlayer.java:131) ~[?:?]
at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.disconnect(VelocityPlayer.java:119) ~[?:?]
... 11 more
```

**Comment by astei** [comment]
Plugin issue

**Comment by KoxSosen** [comment]
Helllo! 

This issue is related to TCPShield, they will have to implement a fix in their plugin to fix this issue. However you're not alone. Multiple people reported the same issue here: #https://github.com/TCPShield/RealIP/issues/87

As the TCPShield documentation, as a workaround, you can enable the proxy protocol on your TCPShield dasboard, and Velocity config. You can find more about that [here](https://docs.tcpshield.com/commonly-asked-questions).

**Comment by xism4** [comment]
> am faced with a problem that constantly torments my proxy server when logging on to the server. Namely, he writes a constant error when a player enters the server. Always writes this message: Couldn't pass ProxyPingEvent to tcpshield
> 
> I tried to use any ways to solve this problem, but it didn't give me anything. All to no avail. Although this error does not interfere with work, it constantly appears.
> 
> ```
> Couldn't pass ProxyPingEvent to tcpshield
> net.tcpshield.tcpshield.util.exception.manipulate.PlayerManipulationException: An exception occured during the handshake process
> at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.disconnect(VelocityPlayer.java:123) ~[?:?]
> at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.handleEvent(VelocityHandshakeHandler.java:51) ~[?:?]
> at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.onProxyPing(VelocityHandshakeHandler.java:45) ~[?:?]
> at net.tcpshield.tcpshield.velocity.handler.Lmbda$37.execute(Unknown Source) ~[?:?]
> at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
> at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler$$Lambda$397/0x0000000089328210.executeAsync(Unknown Source) ~[?:?]
> at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
> at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
> at com.velocitypowered.proxy.event.VelocityEventManager$$Lambda$402/0x0000000089339470.run(Unknown Source) ~[?:?]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
> at java.lang.Thread.run(Thread.java:883) [?:?]
> Caused by: java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.HandshakeSessionHandler$LegacyInboundConnection.connection to com.velocitypowered.proxy.connection.client.ConnectedPlayer
> at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
> at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
> at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
> at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
> at java.lang.reflect.Field.get(Field.java:419) ~[?:?]
> at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.getMinecraftConnection(VelocityPlayer.java:131) ~[?:?]
> at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.disconnect(VelocityPlayer.java:119) ~[?:?]
> ... 11 more
> ```

I just think it caches the ping before or something like that
