### ISSUE TITLE
The uuid is null! With assertion enabled: 1.7 tab list entry given to modern tab list handler!

### ISSUE THREAD

**Issue by Osiris-Team** [PaperMC/Velocity#864]
Happens when a player tries to connect to the lobby server 1.19.2.
I am on the latest velocity snapshot. Full exception when running with assertions enabled:
(when running without it gives nullpointer exception for uuid)
```log
[13:06:06 ERROR]: [server connection] ArkPly -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@5645fb82
java.lang.AssertionError: 1.7 tab list entry given to modern tab list handler!
        at com.velocitypowered.proxy.tablist.VelocityTabList.processBackendPacket(VelocityTabList.java:146) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handle(BackendPlaySessionHandler.java:241) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at com.velocitypowered.proxy.protocol.packet.PlayerListItem.handle(PlayerListItem.java:179) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at net.elytrium.limboapi.injection.packet.PlayerListItemHook.handle(PlayerListItemHook.java:74) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:125) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:58) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velo.jar:VelocityAuth-1.2-Velocity-3.1.2-SNAPSHOT (git-3d07b277-bunknown)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Osiris-Team** [comment]
Nevermind just found out the cause....
