### ISSUE TITLE
BackendPlaySessionHandler exception

### ISSUE THREAD

**Issue by fire7d** [PaperMC/Velocity#878]
I have no clue why this happening, players got kicked to fallback server (from specific gamemode to lobby).

Today I got this:
```
Nickname -> megadrop: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@1884469e
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.PlayerListItem Direction CLIENTBOUND Protocol 1.8 State PLAY ID 38
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.1]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity.jar:3.1.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.1.1]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity.jar:3.1.1]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity.jar:3.1.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity.jar:3.1.1]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.netty.handler.codec.CorruptedFrameException: Trying to read a string that is too long (wanted 63, only have 1)
	at com.velocitypowered.proxy.protocol.util.NettyPreconditions.checkFrame(NettyPreconditions.java:78) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:191) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:182) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:170) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readProperties(ProtocolUtils.java:382) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.packet.PlayerListItem.decode(PlayerListItem.java:73) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity.jar:3.1.1]
	... 24 more
```
but mostly I got this, single line "kick":
```
Nickname -> megadrop: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@4ed63528
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

On the main (gamemode server) I just got:
`Nickname lost connection: Disconnected`

**Comment by Xernium** [comment]
Something is corrupting your player/tablist on the server. Try without plugins, if that doesnt help please switch to a supported backend (eg paper)

**Comment by astei** [comment]
Closing due to lack of response.

**Comment by alexanderdidio** [comment]
Hey I'm having the same issue! Did you ever figure out how to fix this?

**Comment by pingguomc** [comment]
So how should we solve this problem?
