### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/velocitypowered/api/event/lifecycle/ProxyInitializeEvent

### ISSUE THREAD

**Issue by Ixf1nity** [PaperMC/Velocity#891]
```
[00:17:04 ERROR]: Exception in thread "main" com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/velocitypowered/api/event/lifecycle/ProxyInitializeEvent
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
[00:17:04 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
[00:17:04 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
[00:17:04 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:148)[00:17:04 ERROR]:       at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
[00:17:04 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:176)
[00:17:04 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:163)
[00:17:04 ERROR]:       at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
[00:17:04 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:126)
[00:17:04 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[00:17:04 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:87)
[00:17:04 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:69)
[00:17:04 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:59)
[00:17:04 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119)
[00:17:04 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151)
[00:17:04 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343)
[00:17:04 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224)
[00:17:04 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:64)
[00:17:04 ERROR]: Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/velocitypowered/api/event/lifecycle/ProxyInitializeEvent
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
[00:17:04 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
[00:17:04 ERROR]:       at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:69)
[00:17:04 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75)
[00:17:04 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
[00:17:04 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
[00:17:04 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
[00:17:04 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[00:17:04 ERROR]:       ... 21 more
[00:17:04 ERROR]: Caused by: java.lang.NoClassDefFoundError: com/velocitypowered/api/event/lifecycle/ProxyInitializeEvent
[00:17:04 ERROR]:       at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[00:17:04 ERROR]:       at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
[00:17:04 ERROR]:       at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
[00:17:04 ERROR]:       at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
[00:17:04 ERROR]:       at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:804)
[00:17:04 ERROR]:       at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:723)
[00:17:04 ERROR]:       at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:423)
[00:17:04 ERROR]:       at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:92)
[00:17:04 ERROR]:       at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:40)
[00:17:04 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:49)
[00:17:04 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
[00:17:04 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[00:17:04 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[00:17:04 ERROR]:       ... 36 more
[00:17:04 ERROR]: Caused by: java.lang.ClassNotFoundException: com.velocitypowered.api.event.lifecycle.ProxyInitializeEvent
[00:17:04 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:84)
[00:17:04 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61)
[00:17:04 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[00:17:04 ERROR]:       ... 52 more
```

**Comment by electronicboy** [comment]
version? full logs? giant stack trace really doesn't give much to go off

**Comment by electronicboy** [comment]
Actually, this looks like you're tryna run a plugin built for velocity polymer (i.e. 4.0.0) rather than the current dev/release version of velocity
