### ISSUE TITLE
Using AsyncPlayerPreLoginEvent#disallow on Paper causes unexpected disconnect exception in Velocity 

### ISSUE THREAD

**Issue by jok-dev** [PaperMC/Velocity#892]
Using the following code in a Paper plugin:
```
@EventHandler
public void onAsyncPlayerPreLogin(AsyncPlayerPreLoginEvent event) {
    event.disallow(Result.KICK_BANNED, Component.text("You've been kicked!"));
}
```

Causes the following exception in velocity: 
```
Caused by: java.util.concurrent.CompletionException: com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
This is usually because the remote server does not have BungeeCord IP forwarding correctly enabled.
See https://velocitypowered.com/wiki/users/forwarding/ for instructions on how to configure player info forwarding correctly.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-2d072151-bunknown)]
        ... 1 more
```

The expected behaviour is the same as if the player is kicked during a play session, the ConnectionRequestBuilder.Result future should be returned with the kick reason "You've been kicked!", instead of completing exceptionally.

**Comment by jok-dev** [comment]
Turns out this is a bug in ProtocolLib, adding a packet listener for the Login.Server.DISCONNECT packet causes that packet to never be sent, so Velocity sees the disconnect as an invalid disconnect.
