### ISSUE TITLE
Modded (cc-restitched) Command Argument types (the ComputerArgumentType and others) cause error when trying to forward player to 1.19.2 Fabric Server.

### ISSUE THREAD

**Issue by samuelh2005** [PaperMC/Velocity#913]
When I try to connect to my Fabric 1.19.2 server with it being proxied by Velocity I get the following error
```java
[16:25:54 INFO]: [connected player] samuelh2005 (/192.168.0.1:64745) has connected
[16:25:54 INFO]: [server connection] samuelh2005 -> create_pack_1 has connected
[16:25:55 ERROR]: [server connection] samuelh2005 -> create_pack_1: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@5aac4a19
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.19.1 State PLAY ID f
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
        at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:85) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:208) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:86) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        ... 32 more
[16:25:55 INFO]: [connected player] samuelh2005 (/192.168.0.1:64745) has disconnected: Your connection to create_pack_1 encountered a problem.
[16:25:55 INFO]: [server connection] samuelh2005 -> create_pack_1 has disconnected
```
I'm using `Velocity 3.1.2-SNAPSHOT (git-c9e0e14e-b201)` also tried `velocity-3.1.1-98` and on the server `Minecraft 1.19.2 with Fabric Loader 0.14.10`. Also on the server I'm using the `Fabric Proxy-Lite mod (version:  2.3.0)` to support modern player info forwarding.

From my testing with the [Quarry](https://github.com/barneygale/quarry) Python package it seems like the structure of `Packet 15(f)` / the [Commands Packet](https://wiki.vg/index.php?title=Protocol&oldid=17873#Commands) has changed. It seems like 1.19.2 allows null identifiers for Argument Types. With a bit of testing we could find a way to figure out what a null identifier dose.

For now are there any work arounds?

**Comment by samuelh2005** [comment]
Might be related to #907

**Comment by samuelh2005** [comment]
Even tried to use ViaVersion to see if it will help with the packet decoding - but it doesn't seem like it dose.

**Comment by samuelh2005** [comment]
My client is 1.19.2 too.

**Comment by samuelh2005** [comment]
When browsing through the source code it seems like Velocity dose not understand modded command argument types. Is there a way to make Velocity ignore them?

**Comment by samuelh2005** [comment]
Between these two lines https://github.com/PaperMC/Velocity/blob/c9e0e14eb1d8edf7bcc5c8d381bc2c84f8a465c1/proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/AvailableCommands.java#L207-L208
I put a `System.out.println(name);`

It looks like it gets confused when, ~~what ever mod it is~~ (Actually CC- Restitched), sends an argument ~~with the name of '?'~~ (Actually 'computer') and it seems like It dose not have an argument type known to Velocity so this cannot find a [serializer](https://github.com/PaperMC/Velocity/blob/c9e0e14eb1d8edf7bcc5c8d381bc2c84f8a465c1/proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/brigadier/ArgumentPropertyRegistry.java#L83) and throws the exception.
https://github.com/PaperMC/Velocity/blob/c9e0e14eb1d8edf7bcc5c8d381bc2c84f8a465c1/proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/AvailableCommands.java#L208

**Comment by samuelh2005** [comment]
~~Also it seems what ever the mod is, uses a node type of 3!~~(Actually it dosen't) Maybe implement a way to pass through custom node types? Unless trying to decode this type causes a few errors?

**Comment by electronicboy** [comment]
We can't just pass through arbitrary data as we have no idea how to decode
it, at the very least cross stitch should maybe wrap it, but it's not
tenable to modify velocity to try to cater to plugins messing with
implementation details which end up on the wire

**Comment by samuelh2005** [comment]
Now the argument name seems to be decoding properly (I might of left some other files modified before) and its not '?' but 'computer'. Could the mod be ComputerCraft (actually CC restitched)?

**Comment by samuelh2005** [comment]
It looks like it's [definitely CC Restitched](https://github.com/cc-tweaked/cc-restitched/blob/41cff864c4d1cc36341b267fcdf569a002d96694/src/main/java/dan200/computercraft/shared/command/CommandComputerCraft.java#L117).  In its `/computercraft dump` command it takes in an argument called `computer` and with the type of `ComputerArgumentType`! This then causes Velocity to get confused.
 
Now how would Velocity support custom argument types?

**Comment by astei** [comment]
You just described what [CrossStitch](https://modrinth.com/mod/crossstitch) does. Admittedly, I need to release the 1.19.3 version...

**Comment by samuelh2005** [comment]
Thanks I will see if it will work!

**Comment by samuelh2005** [comment]
That works!
