### ISSUE TITLE
Error decoding class com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo Direction CLIENTBOUND Protocol 1.19.3 State PLAY ID 36

### ISSUE THREAD

**Issue by LunarsWorldLLC** [PaperMC/Velocity#924]
Spigot server is latest pufferfish 1.19.3, I'm using the latest version of via*, geyser, and vulcan 3.1.2-SNAPSHOT (git-c9e0e14e-b201)

The issue is SUPER random, just let me explain.

(Theres no way I can replicate it, it's way too random).

After about 1 hour to 24 hours of uptime, with over 150 geyser players online, and 200 java, this error will start being thrown.

It's always a geyser player who triggers it. Essentially, afaik, it's a bedrock player sending/receiving a malformed PLAYER_INFO packet.

Once this happens, nobody can join the server. When you try to join the server, you're met with this error on the velocity proxy.

```
[23:04:25] [Netty epoll Worker #5/ERROR]: [server connection] _Brightnight2313 -> chillsmp: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@3c5ae4f5
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo Direction CLIENTBOUND Protocol 1.19.3 State PLAY ID 36
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.handler.codec.CorruptedFrameException: Trying to read a string that is too long (wanted 9970, only have 4650)
	at com.velocitypowered.proxy.protocol.util.NettyPreconditions.checkFrame(NettyPreconditions.java:78) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:191) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:182) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:170) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo$Action.lambda$static$10(UpsertPlayerInfo.java:180) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo.decode(UpsertPlayerInfo.java:101) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.2-SNAPSHOT-201.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
	... 26 more
```

Theres an additional error on the spigot server when joining.  I'm aware vulcan is in the stack, this issue is still present with vulcan unloaded.

```
[23:08:40] [Netty Epoll Server IO #0/WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[23:08:40] [Netty Epoll Server IO #0/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:08:40] [Netty Epoll Server IO #0/WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at Vulcan-2.7.1 (3).jar//io.github.repooper.packetevents.Vulcan_kw.write(Vulcan_kw.java:60)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:08:40] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:08:40] [Netty Epoll Server IO #0/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:08:40] [Netty Epoll Server IO #0/WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
```

I've already spoken to Camotoy, Kennytv, Vulcan Devs, Eglow Devs, LD Devs, no one can figure this out.

So far I've seen 7 other people reporting this issue throughout various github issue reports.

**Comment by LunarsWorldLLC** [comment]
Other places I've reported this & some have more and or different information.

https://github.com/ViaVersion/ViaBackwards/issues/512
https://github.com/CitizensDev/Citizens2/issues/2974
https://github.com/dmulloy2/ProtocolLib/issues/2083
https://github.com/ViaVersion/ViaRewind/issues/422

**Comment by electronicboy** [comment]
The various reports show that an exception is being thrown over a truncated OUTBOUND packet, meaning that this is before the packet even gets to velocity.

Given that the error seen on velocity is due to an apparently truncated packet, and even stuff in your server is screaming about truncation, this is pretty much 100% going to not be our issues

**Comment by LunarsWorldLLC** [comment]
> The various reports show that an exception is being thrown over a truncated OUTBOUND packet, meaning that this is before the packet even gets to velocity.
> 
> Given that the error seen on velocity is due to an apparently truncated packet, and even stuff in your server is screaming about truncation, this is pretty much 100% going to not be our issues

Would it be a possibility to debug this with a modified version of velocity to listen on what is sending the packet?

**Comment by electronicboy** [comment]
No, your issue exists before velocity, we're just eating dirt from your server, as even via* is complaining about on the backend server
