### ISSUE TITLE
Velocity will not load any plugins if two versions of the same plugin are found

### ISSUE THREAD

**Issue by thecmdradama** [PaperMC/Velocity#955]
Hi guys, 

If someone were to upload two versions of a plugin to Velociyu i.e. LuckPerms-Velocity-5.4.30.jar and LuckPerms-Velocity-5.4.62.jar. The current behavior is to skip loading plugins and continue starting.

```
[13:05:54 ERROR]: Couldn't load plugins
java.lang.IllegalArgumentException: Multiple entries with same key: luckperms=VelocityPluginDescription{id='luckperms', name='LuckPerms', version='5.4.30', description='A permissions plugin', url='https://luckperms.net', authors=[Luck], dependencies={}, source=plugins/LuckPerms-Velocity-5.4.30.jar} and luckperms=VelocityPluginDescription{id='luckperms', name='LuckPerms', version='5.4.62', description='A permissions plugin', url='https://luckperms.net', authors=[Luck], dependencies={}, source=plugins/LuckPerms-Velocity-5.4.62.jar}. To index multiple values under a key, use Multimaps.index.
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1281) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1236) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
	at com.velocitypowered.proxy.plugin.util.PluginDependencyUtils.sortCandidates(PluginDependencyUtils.java:63) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:108) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]
[13:05:54 INFO]: Loaded 0 plugins
```

Realistically, server admins should ensure that they clean up the older version(s) of a plugin and restart Velocity.

However could this be adjusted so that Velocity ignores the older version of the plugin and proceed to loading the next plugin.

**Comment by electronicboy** [comment]
There is no stable way to determine the oldest version of a plugin, and this is generally not something in our ball court
