### ISSUE TITLE
Problem with commands /premium

### ISSUE THREAD

**Issue by TheDamStex** [PaperMC/Velocity#959]
ava.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command premium confirm for [connected player] TheDamStex21 (/)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command premium  confirm for [connected player] TheDamStex21 (/)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:251) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at net.elytrium.limboauth.LimboAuth.isPremiumExternal(LimboAuth.java:692) ~[?:?]
        at net.elytrium.limboauth.command.PremiumCommand.execute(PremiumCommand.java:80) ~[?:?]
        at net.elytrium.limboauth.command.PremiumCommand.execute(PremiumCommand.java:34) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:213) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:251) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at net.elytrium.limboauth.LimboAuth.isPremiumExternal(LimboAuth.java:692) ~[?:?]
        at net.elytrium.limboauth.command.PremiumCommand.execute(PremiumCommand.java:80) ~[?:?]
        at net.elytrium.limboauth.command.PremiumCommand.execute(PremiumCommand.java:34) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:213) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:251) ~[velocity.jar:3.2.0-SNAPSHOT (git-7da4f260-b231)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more

**Comment by astei** [comment]
This is a plug-in issue, further we don’t support offline mode
