### ISSUE TITLE
AnnotatedConnectException error on player join

### ISSUE THREAD

**Issue by Supermarcel10** [PaperMC/Velocity#965]
## Information
Velocity throws an error whenever a player attempts to join through the Velocity proxy. The temporary lobby server for testing is running version 1.12.2. Visible message "Unable to connect you to lobby. Please try again later".

Attempted to try disabling online-mode in an attempt to get it working, and then figure it out from there, but it seems like it's a consistent issue. Error shows up no matter the client version.

## Velocity Setup
Velocity Version: `velocity-3.2.0-SNAPSHOT-232`
Local IP: 192.168.1.27:25570
Java version:
```
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```

## Server Setup
Paper Version: git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Local IP: 192.168.1.27:25572
BungeeGuard Version: v1.3-SNAPSHOT
BungeeGuard config:
```
allowed-tokens:
  - "XXXXXXXXXXXX"
```
Java version:
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```

## `Velocity.toml`
```
bind = "0.0.0.0:25570"
online-mode = true (tried both true and false)
force-key-authentication = true (tried both true and false)
prevent-client-proxy-connections = true (tried both true and false)
player-info-forwarding-mode = "bungeeguard"
forwarding-secret-file = "forwarding.secret"
ping-passthrough = "all"

[servers]
lobby = "127.0.0.1:25572"
try = [
	"lobby"
]

tcp-fast-open = false
```

## Error
```
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:25566
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-232.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by electronicboy** [comment]
> Connection refused: /127.0.0.1:25566

The server you apparently connected to refused the connection, this is not a velocity issue as the error is external and is generally an issue with network config/"is the server running"

**Comment by Supermarcel10** [comment]
> > Connection refused: /127.0.0.1:25566
> 
> The server you apparently connected to refused the connection, this is not a velocity issue as the error is external and is generally an issue with network config/"is the server running"

Any idea why it would be connecting to 127.0.0.1:25566?
Any suggestions as to what could be the general issue?

**Comment by electronicboy** [comment]
I can't say why it would be connecting to that, it doesn't line up with your config excerpt that you've provided, but, I can't really say without knowing more about your proxy, and that's more of a support topic best left to the discord/forums rather than the bug tracker
