### ISSUE TITLE
EpollEventLoop

### ISSUE THREAD

**Issue by HanielCota** [PaperMC/Velocity#981]
: unable to connect to server lobby
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:25644
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:164) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:129) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[proxy.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by astei** [comment]
Connection refused means the server is not online or is refusing connections. Please check the server and make sure you're using the right hostname and port.
