### ISSUE TITLE
Velocity 'A Java Exeption has occurred' or place file somewhere.

### ISSUE THREAD

**Issue by Nino3245** [PaperMC/Velocity#982]
When Launching 'velocity-3.2.0-SNAPSHOT-244' Java throws an exeption. Anything I can do to fix Java or is it a bug with the software?
Also do I need to put the file somewhere to load it.

**Comment by Nino3245** [comment]
Wait I'm looking online

**Comment by Nino3245** [comment]
Wait I tried running the start.bat program I made
And it threw :
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/velocitypowered/proxy/Velocity has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Press any key to continue . . .`

**Comment by astei** [comment]
You have an outdated version of Java, Velocity requires Java 11 or higher

**Comment by Warriorrrr** [comment]
Velocity requires at least java 11 to run, see https://docs.papermc.io/velocity/getting-started#installing-java.

**Comment by Nino3245** [comment]
Well I found out I don't need to install a newer version of Java and I fixed the bug

**Comment by Xernium** [comment]
> Well I found out I don't need to install a newer version of Java and I fixed the bug

Velocity does not run on Java 8 (which is the version you're running as indicated by the error).
Therefore this comment is misleading. You would have to alter the velocity source code for it to compile and run on Java 8 and it will only run with Java 11 or newer in an unaltered form

**Comment by Nino3245** [comment]
Hmm Interesting

**Comment by Nino3245** [comment]
I just picked an older version of Velocity anyway

**Comment by Xernium** [comment]
You would have had to pick a 1.x or an old 3.0.x release for that to work. I strongly suggest to not use it. These old versions are susceptible to the critical Log4J security vulnerability and considered a severe security risk
